### PR TITLE
Fxt update

### PR DESCRIPTION
**Pull request by klendathu2k**

### CODE REVIEW

**Review by iraklic — APPROVED** [review]

**Comment by genevb** [comment]
I see that the 2018 fixed target position was also modified. This may not be justified as yet. My understanding is that the beampipe was removed between 2018 and 2019 for the detector rollout and installation of the iTPC. As such, the 2018 position may be different relative to STAR from the 2019+ position. I understand that the 2018 FXT position of 200.7 was identified in Fig. 19, page 26 of this analysis note:
https://drupal.star.bnl.gov/STAR/system/files/Analysis_Note_for_Higher_Order_Cumulants_FXT_Au_Au_3_0_GeV.pdf

So we probably only want to adjust 2019-2021 geometries to use z = 200.0 cm for now.

**Comment by klendathu2k** [comment]
Thanks Gene.  y2018d removed.

**Review by genevb — APPROVED** [review]
LGTM.

**Comment by genevb** [comment]
> LGTM.

Well.... better to understand the build failure before merging.

**Comment by klendathu2k** [comment]
Build issue was a duplicate entry for y2024a coupled with hubris on my part not to compile locally before making the PR.  Second entry should have been tagged as y2024b.  Code compiles locally, so I expect this to compile on github.

**Comment by klendathu2k** [comment]
All tests are passing, so hitting the shining green button.

**Pull request merged**
