### PR TITLE
Star tablelib

### PR DESCRIPTION
**Pull request by klendathu2k**
This commit brings libTable back into the STAR repository.  It is integrated under StRoot/Table.  Header files are exported into $STAR_HOST_SYS/include.

We need to be able to handle the case where we are compiling / linking against a version of ROOT which provides libTable.  The only reliable way to do this is to check the features supported by ROOT.  cons has been modified to check whether ROOT supports libTable.  If it does, no libTable is created and headers are not exported.  

Several small fixes to STAR codes are included in this PR, which are required to compile against ROOT 6.

Compilation in the DEV environment (ROOT 5) was tested and works.

Compilation against ROOT 6 was tested.  Everything compiled and root4star runs.  (Except for StiCA b/c I did not setup Vc...  we'll see if it compiles in the CI environment).

### CODE REVIEW

**Review by dmarkh — APPROVED** [review]
LGTM

**Review by perevbnlgov — APPROVED** [review]
No objections

**Review by genevb — COMMENTED** [review]
No objections

**Review by veprbl — APPROVED** [review]
LGTM

**Comment by kehw** [comment]
There are a few unrelated files, adding header and such. Other than that, looks good.

**Review by kehw — APPROVED** [review]

**Review by starsdong — APPROVED** [review]
Looks good to me too.

**Review by plexoos — APPROVED** [review]
Welcome home TTable 🥲

**Comment by klendathu2k** [comment]
A 20 year journey comes full circle ;)

Almost.  Needs approvals from 4 code owners for the small changes made 
to their codes...

**Review by akioogawa — APPROVED** [review]

**Review by nigmatkulov — APPROVED** [review]
Looks good.

**Comment by plexoos** [comment]
The critical approval needs to come from @tinglin-physics who is the sole maintainer of the modified StRoot/StEEmcPool/muEztPanitkin/EEqaPresenter.cxx 

https://github.com/star-bnl/star-sw/blob/cb94f7c8a92f018d54956709fb18382767532ba0/.github/CODEOWNERS#L45

**Review by tinglin-physics — APPROVED** [review]

**Comment by klendathu2k** [comment]
Pressing the magic green button to merge.

**Pull request merged**
