### PR TITLE
[root6] Rename s/ostrstream/St_ostrstream/

### LINKED ISSUE #126: Error due to ambiguous ostrstream while running bfc.C in ROOT6
When I try to run one of our tests in ROOT6 environment I get the following error:

```
Processing bfc.C(10, "pp2017,StiCA,btof,mtd,pp2pp,fmsDat,fmsPoint,fpsDat,BEmcChkStat,QAalltrigs,CorrX,OSpaceZ2,OGridLeak3D,-hitfilt", "/star-test-data/quick/st_physics_18069061_raw_2000021.daq")...
In file included from input_line_37:1:
In file included from /star-sw/StRoot/macros/bfc.C:19:
In file included from /star-sw/.sl88_gcc789/include/StBFChain.h:22:
In file included from /star-sw/.sl88_gcc789/include/StChain.h:22:
In file included from /star-sw/.sl88_gcc789/include/StMaker.h:26:
/star-sw/.sl88_gcc789/include/StMessMgr.h:108:26: error: reference to 'ostrstream' is ambiguous
class StMessMgr : public ostrstream {
                         ^
/star-sw/.sl88_gcc789/include/Stsstream.h:15:7: note: candidate found by name lookup is 'ostrstream'
class ostrstream : public std::ostringstream {
      ^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/backward/strstream:143:9: note: candidate found by name lookup is 'std::ostrstream'
  class ostrstream : public basic_ostream<char>
```

Any suggestions how to fix this? @perevbnlgov @klendathu2k

### PR DESCRIPTION
**Pull request by plexoos**
Fixes #126 Error due to ambiguous ostrstream while running bfc.C in ROOT6

### CODE REVIEW

**Review by genevb — COMMENTED** [review]
I have no objection to replacing ostrstream with St_ostrstream in the logger / message manager. What people are doing with ostrstream outside of that, I don't know.

**Comment by dmarkh** [comment]
Personally, I never understood a need for St_* streams. Victor explained that they needed during times when STL was unstable and they encountered issues with streams - thus wrapper was created. In my code (StDbLib), I never expect St_* streams, but rather standard std:: streams. Moreover, StDbLib cannot depend on ROOT, as it has a standalone compile option - used by Jeff in the online domain. If St_* streams are ROOT-dependent, please do not use them as a substitute for std:: streams in the StDbLib codes.

**Comment by perevbnlgov** [comment]
I do not remember all the history, but as a result
we have class
class ostrstream : public std::ostringstream {
But there is an official std::ostrstream.
In very old code there were methods :

const char *str()
int   pcount() const
void freeze(bool)

which are not in ostrstream.
So this fake ostrstream was used.
But when Root6 + new compiler is used this compiler found
that there are two ostrstring classes, one in Star code and one in std::
and clashes arised.

Now I replaced my class ostrstring to St_ostrstring
and added #define ostrstream St_ostrstream
No clashes any more

**Comment by plexoos** [comment]
> Now I replaced my class ostrstring to St_ostrstring and added #define ostrstream St_ostrstream
> No clashes any more

First, I think you meant to say that you did s/ostrstream/St_ostrstream/ rather than s/ostrstring/St_ostrstring/
This is exactly what this PR is proposing to do across the entire code base.

Then, why do you think the `#define ostrstream St_ostrstream` is necessary?

Finally, if you look at the result of the CI checks (which you can access from this PR page) you see that the code with the above modification compiles fine but the test jobs in ROOT5 fail with the following message:

```
Error: operator<< not defined for St_ostrstream /star-sw/StRoot/macros/bfc.C:144:
Error: << Illegal operator for pointer 3 /star-sw/StRoot/macros/bfc.C:144:
*** Interpreter error recovered ***
```

So, clearly just the renaming of ostrstream to St_ostrstream is not enough to take care of this problem.

**Comment by plexoos** [comment]
I don't know if Jason is back from his vacation but he wanted to try something different https://github.com/star-bnl/star-sw/issues/126#issuecomment-907532000

I think the idea was to replace the STAR's ostream with `std::ostringstream`. If @klendathu2k can come up with a nice PR for this we can see if it works.

**Comment by klendathu2k** [comment]
Hi Dmitri,

I am back from vacation.  I'll assemble a PR this weekend.

Jason

**Comment by perevbnlgov** [comment]
> s/ostrstream/St_ostrstream/ rather than s/ostrstring/St_ostrstring/
No, every there in the Star code is used ostrstream

> This is exactly what this PR is proposing to do across the entire code
> base.
    I do not want to change the entire code. In addition ostringstream 
does not have
    method const char* str(). It has std::string str(). So you must 
change also all using of str()
    I do not think that at the end of STAR we need to change a lot of 
code. (obout 100+ lines)

> Then, why do you think the #define ostrstream St_ostrstream is
> necessary?
As I explained to avoid clash between fake ostrstream and the real one.
Everywhere where is declared #include Sstrstream this #define will 
convert it into
St_ostrstream and everywhere where there is no such include and hence no 
#define,
the official std::ostrstream will be used. As a result no clash.

> Error: operator<< not defined for St_ostrstream
> /star-sw/StRoot/macros/bfc.C:144:
> Error: << Illegal operator for pointer 3
> /star-sw/StRoot/macros/bfc.C:144:
No this is fixed

Victor

**Comment by plexoos** [comment]
I believe we still don't have a working solution for #126 among the existing PRs

**Comment by perevbnlgov** [comment]
Do you mean that my solution does not work?
If so, please show me where I can see it.

**Comment by plexoos** [comment]
> Do you mean that my solution does not work? If so, please show me where I can see it.

Did you create a pull request with your solution?

**Comment by perevbnlgov** [comment]
In my Star6 origin there is the class
class St_ostrstream : public std::ostringstream {

But in the main Star6 repository
class ostrstream : public std::ostringstream {

In my comments I have:
In StMessage.h ostrstream replaced tp std::St_ostrstreamm, see 
Stsstreamm.h comments.
In Stsstream.h ostrstream was replaced by std::St_ostrstream to avoyd 
clash with real ç
and #define std::St_ostrstream ostrstream, to avoid clash with the real 
ostrstreamm

I did all the pull requests and I do not know why my updates were not 
propagated.
But this github is so complicated that I can nor be sure in anything

Victor

**Comment by plexoos** [comment]
>  I do not know why my updates were not propagated.

We cannot merge changes if they cause errors in our builds. You did create a few PRs but none of them passed the test build successfully. For example, see errors here https://github.com/star-bnl/star-sw/pull/130/checks?check_run_id=3477975211

**Comment by klendathu2k** [comment]
Hi Victor,

Bottom of the pull request page...
https://github.com/star-bnl/star-sw/pull/134
... it doesn't pass tests...

Digging into the test, it looks like it fails when a bfc.C macro is 
loaded
under ROOT5.  That would break all production chains...

Cheers,
Jason

**Comment by perevbnlgov** [comment]
Looking on compilation I see the problem with StShadowMaker and 
StarGeoetry.
No one of them was modified by me. my compilation is successful.

Victor

**Comment by plexoos** [comment]
Victor, Are you looking at this line? https://github.com/star-bnl/star-sw/pull/130/checks?check_run_id=3477975211#step:3:15375

`
#21 ERROR: process "/bin/bash -c source /etc/profile  && export Vc_DIR=/opt/software/linux-scientific7-x86_64/gcc-4.8.5/vc_-0.7.4-gqbhzu2x5u2dbe5tafxnl36xj5qbwov4  && cd /star-sw  && cons +StarVMC/Geometry  && cons %OnlTools          %StRoot/StShadowMaker  && find /star-sw/.$STAR_HOST_SYS -name *.o -exec rm '{}' \\;" did not complete successfully: exit code: 2
`

You need to look at the lines prior to this one.

The problem is not with either `StarVMC/Geometry` or `StShadowMaker` which is excluded form the build

**Comment by plexoos** [comment]
I am not sure what you mean by "your" compilation. The CI jobs build the entire code base (with the exception of `StShadowMaker`)

Actually, you probably want to comment about the compilation problems in your PR #130
This PR #134 has a problem with ostrstream in run time

**Comment by perevbnlgov** [comment]
On 2021-09-15 13:09, Dmitri Smirnov wrote:
> I am not sure what you mean by "your" compilation. The CI jobs build
> the entire code base (with the exception of StShadowMaker)
It is very simple. I have full code in the local repository and it
compiled without errors

**Comment by perevbnlgov** [comment]
I found that the problem in StHbtMaker. It is out of my compilation. It 
is no used anymore.
Last comment was 7 years ago.

**Comment by plexoos** [comment]
Superseded by #150

**Pull request closed without merging**
