### PR TITLE
StEvent StTriggerData2022 update associate with 

### PR DESCRIPTION
**Pull request by akioogawa**
StEvent StTriggerData2022 update associate with removing some EPD DSM from trigger structure for run22

### CODE REVIEW

**Review by ullrich-bnl — APPROVED** [review]

**Comment by akioogawa** [comment]
holding the PR.... until trigger group discussion tomorrow

**Comment by akioogawa** [comment]
Trigger group may decide leaving trgStructure as is. Still changes in StEvent StTriggerData2022 is needed.

**Comment by akioogawa** [comment]
@klendathu2k, I need this quick. Please review. Thanks!

**Comment by plexoos** [comment]
Akio, there should be very little if any need for your critical work to depend on being on the main branch in this repo even less on anyone's approval. From your comment I suspect that your workflow may not be optimal. If you want to discuss this please let me know and I'll make myself available.

**Review by plexoos — APPROVED** [review]

**Review by klendathu2k — APPROVED** [review]
Looks reasonable.  Note that there are function calls and definitions which are commented out, rather than being removed.  This could cause confusion when people look at the code later on.  In an ideal world, these would be deleted rather than commented out.  Alternatively, documentation.  Regardless, no need to hold up getting this integrated any further.

**Comment by klendathu2k** [comment]
Pressing the magic green button...

**Pull request merged**
