### PR TITLE
Guannan's tune up for 7p7GeV_2021, https://www.star.bnl.gov/~xgn1992/…

### PR DESCRIPTION
**Pull request by fisyak**
…star/Tpc/2021/7p7GeV_2021/TFG23a_revisit8/index.html, mv TF1F to StarRoot

### CODE REVIEW

**Comment by starsdong** [comment]
Thanks, Yuri and Guannan. I see the change is done for the TpcResponseSimulator.y2008.C, does this mean it applies to all simulations after y2008?

**Comment by fisyak** [comment]
Hi Xin, TpcResponseSimulator.y2008.C is applied to run 8 only. The run 8  is the first run where we had ALTRO cheap. But for this run ALTRO did not have any tail cancellation parameters. The first run with tail cancellation was run 9.

**Review by iraklic — APPROVED** [review]

**Comment by starsdong** [comment]
Thank you, Irakli for reviewing this. Thank you, Yuri for the update of cleaning up of the tpcRDOMask tables from previous commit (PR#500). This PR looks to be urgently needed for both 7.7 GeV embedding and library built for upcoming OO production. Jason, Dmitry (also Xianglei), if you can help review it and comment/approve this PR soon. Thanks

**Review by dmarkh — APPROVED** [review]
Looks good to me.

**Review by zhux97 — APPROVED** [review]

**Comment by starsdong** [comment]
Thank you all for confirming and thank Yuri for taking extra care of the clean-up of the StarDb tables. I think this PR is ready to be merged.

**Pull request merged**
