### PR TITLE
Star6

### PR DESCRIPTION
**Pull request by perevbnlgov**
"Cons" changes for Root6, merging of DEV Cons + Y.Fisyak + VP. Cons  in STAR itself  over complicated code.
It is very hard to support. Probably in future it is better to move to CMAKE. Current version does not work yet
for "pams" with non standard Fortran code.

StarGenerator: Full version. Buf i Cons fixed and now full version compiles successfully.

Some old SAR code, based on Root5 features and not used now is obsolete.
Few technical changes for for Root6.

### CODE REVIEW

**Comment by dmarkh** [comment]
Ahem, "Files changed: 5,000+" May take quite some time to review changes thoroughly ;)

**Comment by plexoos** [comment]
It looks this PR was created from the `Star6` branch in this repo `star-bnl/star-sw`. But I think the original intention was to use the 'Star6' branch in the `perevbnlgov/star-sw` fork.

Again, here is the link to create a more reasonable PR

https://github.com/star-bnl/star-sw/compare/main...perevbnlgov:Star6

I suggest you close this pull request and create a new one using the link above

**Comment by starsdong** [comment]
Hi Victor,

It is nice to see you push this forward. Thanks. Is it still possible for you to join today's S&C management meeting and discuss about the plan and how to proceed.
https://drupal.star.bnl.gov/STAR/event/2021/07/14/sc-management-meeting

**Comment by plexoos** [comment]
Yes, it is nice to see the progress... But I would also like to draw everyone's attention to already available and pending changes addressing some problems with integration of ROOT6 in https://github.com/star-bnl/star-sw/pull/47

**Comment by perevbnlgov** [comment]
Hi Xin,
sorry, I thought that there is no meeting today. Probably I missed some 
email.
Victor

**Comment by plexoos** [comment]
As noted above this PR was not created properly

**Pull request closed without merging**
