### PR TITLE
[JevpProduction] Add online TOT histograms for MTD

### PR DESCRIPTION
**Pull request by marrbnl**

### CODE REVIEW

**Comment by veprbl** [comment]
@marrbnl  Did you mean to submit this against the "JevpProduction" branch?

**Comment by marrbnl** [comment]
It looks like it is submitted against the main branch. Should I submit to "JevpProduction" branch? If so, how can I do that? Thanks.

**Comment by veprbl** [comment]
@marrbnl You can click "Edit" button to the right of your PR's title, then change the value of the "base:" dropdown menu. You might need to do `git rebase -i JevpProduction` to remove unrelated commits and `git push -f` after that.

**Comment by veprbl** [comment]
Sorry for the noise, guys.

@marrbnl You didn't do anything wrong. It's a known GitHub bug with CODEOWNERS and base change. It just needs a rebase and force push (I guess in this case you should first do that).

**Comment by marrbnl** [comment]
Here is what I did: 
git rebase JevpProduction
git push -f origin rma-online-mtd

I changed the base from main to JevpProduction for this PR, but now it says my PR requests 40 commits, which seems wrong

**Comment by veprbl** [comment]
`git rebase -i JevpProduction `, then remove all lines except the one with your commit, save, exit, then `git push -f`

**Comment by marrbnl** [comment]
When I do "git rebase -i JevpProduction", only an empty scratch pops up. I do not see any commits

**Comment by veprbl** [comment]
You almost made it. Judging from `git log be0c68b85e --format=full` you've closed the file without removing the extra commit history from "main". I've fixed it by basically doing a `rebase` again: https://asciinema.org/a/ydvQfiB2yzsTqpan6gpGXIhxo

**Comment by marrbnl** [comment]
Thanks very much.

**Comment by fgeurts** [comment]
Code changes look fine.

**Comment by fgeurts** [comment]
Thanks for reopening. I mixed up my review/approval buttons.

**Comment by starsdong** [comment]
Do we understand the failure in CI Build with ROOT5? Can we fix it and move the request forward? Thanks

**Comment by veprbl** [comment]
The failure on the "JevpProduction" branch is a known issue and needs to be addressed separately from this PR.

**Comment by starsdong** [comment]
Closing this old PR. Jevp is update-to-date with a recent PR by Jeff.
https://github.com/star-bnl/star-sw/pull/292

**Pull request closed without merging**
