### PR TITLE
Fix issues when compiling against ROOT6

### PR DESCRIPTION
**Pull request by plexoos**
Unlike rootcint, rootcling in ROOT6 seems to be mindful of the access modifiers for nested types used to declare data members. Such types should have public access

### CODE REVIEW

**Review by fgeurts — APPROVED** [review]
I see no issues with the proposed changes.

**Comment by klendathu2k** [comment]
Regarding changes to  StRoot/StEvent/StEmcDetector.cxx 

I have never understood the purpose of (or history behind) StAutoBrowse.  Changes look harmless / touch functionality, not event model.  However, this code is in StEvent, and so @ullrich-bnl should review.

**Comment by perevbnlgov** [comment]
It is written by me. It is automatic Browser, to avoid manual encoding 
all included classes.
It was not implemented in ROOT. Later Rene add this functionality in 
ROOT.
Now it is possible to remove.
Victor

**Comment by plexoos** [comment]
Any more approvals from the code owners?

**Comment by plexoos** [comment]
If I don't hear any further comments from anyone including @ullrich-bnl I'll merge this PR tomorrow.

**Pull request merged**
