### PR TITLE
Summer 2023 updates

### PR DESCRIPTION
**Pull request by jml985**

### CODE REVIEW

**Comment by jml985** [comment]
I don't have any idea what the update "adding PWGTools" was for or meant.   It doesn't actually have any effect or bearing on what I'm doing which is trying add in changes from StRoot/RTS.     I did just add one more change to the file StRoot/RTS/src/DAQ_TPC23/itpc23.h.     In order to do this I needed to fetch and merge to my local directory, which had no effect considering I have only StRoot/RTS enabled for download.  It did allow me to push it to my local github/main however.

**Comment by plexoos** [comment]
The compilation is failing with this error:

```
#10 136.6 g++ -m64 -fPIC -pipe -Wall -Woverloaded-virtual -std=c++0x -Wno-long-long -pthread -Wno-deprecated-declarations -O2 -g -falign-loops -falign-jumps -falign-functions -Dsl79_gcc485 -D_LARGEFILE64_SOURCE -DNEW_DAQ_READER -DRTS_PROJECT_STAR -DTPXREADER -DRTS_LITTLE_ENDIAN -DEVP_VERSION="\"EVP_VERSION=2.0\"" -DNEW_DAQ_READER -I. -IStRoot/RTS/include -IStRoot/RTS/trg/include -IStRoot/RTS/include/TPC -IStRoot/RTS/src/SFS -IStRoot/RTS/src -IStRoot/RTS/src/EVP_READER -I. -IStRoot -I.sl79_gcc485/include -I/opt/software/linux-scientific7-x86_64/gcc-4.8.5/root-5.34.38-l3v6vso6qgojm4l2ctwjojs6trbt4hpn/include -c .sl79_gcc485/OBJ/StRoot/RTS/src/DAQ_TPC23/itpc23.cxx -o .sl79_gcc485/OBJ/StRoot/RTS/src/DAQ_TPC23/itpc23.o
#10 136.6 .sl79_gcc485/OBJ/StRoot/RTS/src/DAQ_TPC23/itpc23.cxx:37:45: error: no 'void itpc23::set_rdo(int, int)' member function declared in class 'itpc23'
#10 136.6  inline void itpc23::set_rdo(int sec, int rdo)
#10 136.6                                              ^
#10 136.6 cons: *** [.sl79_gcc485/OBJ/StRoot/RTS/src/DAQ_TPC23/itpc23.o] Error 1
#10 136.6 cons: errors constructing .sl79_gcc485/OBJ/StRoot/RTS/src/DAQ_TPC23/itpc23.o
```

@jml985 are you going to look into this?

**Comment by jml985** [comment]
Sorry I had tried to fix some problems I thought Tonko had introduced, but they were actually due to my own mess...   I've updated with tonko's changes and will see if they pass the CI

**Review by plexoos — APPROVED** [review]
The code compiles now

**Comment by starsdong** [comment]
Dmitri, let us merge this PR into main (do we need to update and sync with the main first?) Thanks

**Comment by plexoos** [comment]
> Dmitri, let us merge this PR into main (do we need to update and sync with the main first?) Thanks

There are no reported conflicts, should be able to merge as is

**Pull request merged**
