### PR TITLE
Fix for StFcsDmMaker->StFcsDb change

### LINKED ISSUE #35: StFcsMIPMaker doesn't compile on main branch
### Steps to reproduce

On RACF run:
```bash
git clone https://github.com/star-bnl/star-sw.git
cd star-sw
git checkout d660bf34b885496c2a36c5ef6f709a96b02cbe49
env -i PATH=$PWD/mgr:$PATH QTDIR=/usr/lib64/qt-3.3 QTINC=/usr/lib64/qt-3.3/include QTLIB=/usr/lib64/qt-3.3/lib CERN_LEVEL=pro CERN=/cern CERN_ROOT=/cern/pro ROOTSYS=/afs/rhic.bnl.gov/star/ROOT/5.34.38/.sl73_gcc485/rootdeb ROOT=/afs/rhic.bnl.gov/star/ROOT ROOT_LEVEL=5.34.38 STAR_SYS=x8664_sl7 STAR_HOST_SYS=sl73_gcc485 OPTSTAR=/opt/star/sl73_gcc485 XOPTSTAR=/afs/rhic.bnl.gov/opt/star/sl73_gcc485 STAR_ROOT=/afs/rhic.bnl.gov/star STAR=/nowhere sh -c '. $ROOTSYS/bin/thisroot.sh; exec cons'
```

Observe:
```
g++ -m32 -fPIC -pipe -Wall -Woverloaded-virtual -std=c++0x -Wno-long-long -pthread -g -Dsl73_gcc485 -D__ROOT__ -DNEW_DAQ_READER -I. -IStRoot -I.sl73_gcc485/include -I/afs/rhic.bnl.gov/star/ROOT/5.34.38/.sl73_gcc485/rootdeb/include -c .sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx -o .sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.o
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx: In member function 'virtual Int_t StFcsMIPMaker::Init()':
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx:45:32: error: 'class StFcsDbMaker' has no member named 'readPedFromText'
       if(mPedSub>0) mFcsDbMkr->readPedFromText();
                                ^
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx:51:53: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
       char* nameEHP[kFcsEHP] = {"Ecal","Hcal","Pres"};
                                                     ^
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx:51:53: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx:51:53: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx:52:46: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
       char* nameNS[kFcsNorthSouth] = {"N","S"};
                                              ^
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx:52:46: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx:60:23: error: 'class StFcsDbMaker' has no member named 'northSouth'
  int ns  = mFcsDbMkr->northSouth(det);
                       ^
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx:61:23: error: 'class StFcsDbMaker' has no member named 'ecalHcalPres'
  int ehp = mFcsDbMkr->ecalHcalPres(det);
                       ^
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx:62:31: error: 'class StFcsDbMaker' has no member named 'maxId'
        int maxid = mFcsDbMkr->maxId(det);
                               ^
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx:70:15: error: 'class StFcsDbMaker' has no member named 'getDepfromId'
    mFcsDbMkr->getDepfromId(det,id,ehp2,ns2,crt,sub,dep,ch);
               ^
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx: In member function 'virtual Int_t StFcsMIPMaker::Make()':
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx:145:33: error: 'class StFcsDbMaker' has no member named 'getStarXYZfromColumnRow'
  StThreeVectorF xyzE=mFcsDbMkr->getStarXYZfromColumnRow(1,clusterE->x(),clusterE->y());
                                 ^
.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.cxx:163:37: error: 'class StFcsDbMaker' has no member named 'getStarXYZfromColumnRow'
      StThreeVectorF xyzH=mFcsDbMkr->getStarXYZfromColumnRow(3,clusterH->x(),clusterH->y());
                                     ^
cons: *** [.sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.o] Error 1
cons: errors constructing .sl73_gcc485/obj/StRoot/StSpinPool/StFcsMIPMaker/StFcsMIPMaker.o
```

### Expected result

Everything compiles without errors

cc @akioogawa

### PR DESCRIPTION
**Pull request by akioogawa**
Fix for StFcsDmMaker->StFcsDb change on Fcs MIP and Pi0 Maker (Closes #35)
Added TOF cut on trigger filter
All in spin pool and nothing to do with BFC & production

### CODE REVIEW

**Comment by akioogawa** [comment]
star-sw/.github/CODEOWNERS list me for StSpinPool, yet I don't see me in reviewer. Is it because I made request? I don't need to approve of anything?

**Comment by plexoos** [comment]
You are not asked to review the changes because you are the one who submitted them. Makes sense to me as implicitly you do "approve" them by wanting them on the main branch

**Comment by veprbl** [comment]
Since there are two changes, it would make sense to review them in separate PRs.

**Review by veprbl — APPROVED** [review]

**Review by plexoos — APPROVED** [review]

**Comment by plexoos** [comment]
I don't think squashing the entire PR is appropriate here but I'd squash the reverted changes into the original commit

**Comment by veprbl** [comment]
@akioogawa Thank you for providing the fix!

**Pull request merged**
