### PR TITLE
Star6

### PR DESCRIPTION
**Pull request by perevbnlgov**
Mgr changes:
1. $CXXFLAGS exactly as in Root6.24 It is the hope that will be less problem with Cling
2. Map Root option for Star as well. Again the hope that will be less problem with Cling.
   But right now these map files not yet moved into lib it is still ignored
3. Added RootCling.pl file for the future development

### CODE REVIEW

**Comment by starsdong** [comment]
Hi Victor, Thank you very much for pushing this forward. I have a few questions regarding the integration plan and how should we do with this PR?

- I think it is good to use the star-bnl:Star6 branch when preparing for the integration of whole ROOT6 related changes. I just wonder whether the approach is agreed with other experts? Dmitri, Gene, Jason etc?

- Regarding this PR, it is not clear what are the main changes. I see lots of the changed files are not particularly related to the ROOT6 update, but seems to keep the star-bnl:Star6 branch update to date, e.g. lots of RTS reader updates, forward software updates etc. For this purpose, I am wondering would it be better to merge these changes from the star-bnl:main branch to Star6 instead coming from individual's private repo?

Please feel free to comment/suggest. Thanks

**Comment by perevbnlgov** [comment]
H Xin,
> I think it is good to use the star-bnl:Star6 branch when preparing for
> the integration of whole ROOT6 related changes.

This branch Star6 is rather old. It was created in the times of CVS and
now it is in GitHub.
> I just wonder whether
> the approach is agreed with other experts? Dmitri, Gene, Jason etc?
You are right, it is a problem. While I do modifications into this 
branch,
Jason, Dmitri, ... do modifications into the main branch. As a result, 
for instance, some changes made by D.Kalinkin, was already done months 
ago.
So, of course, it is more safe to put it into separate branch.

Few days ago, I did merging of all changes (made Jason+Dmitri) plus my 
changes
and put them into GitHub. It became too complicated for GitHub, and it 
lost
it's mind. Jason proposed me to do it separately by few pieces. The 
piece you have seen is a first one. I tried to do the next one, but 
GitHub refuse to do it. Now I am trying to understand why.

> this purpose, I am wondering would it be better to merge these changes
> from the star-bnl:main branch to Star6 instead coming from
> individual's private repo?

I think you are right. But it was a lot of modifications in "origin" 
which
were not accepted. As a result, this "origin" became a pile of garbage. 
Some modifications were not propagated from the August of previous year. 
Unfortunately I am not an expert in GitHub, which is hundred times more 
complicated and less user friendly than CVS.I found the way how to 
delete
Star6 in "origin" and do the merge main+Star6 and put it into "origin" 
as a commit. It is not a good approach, and next time I will do it more 
official way

Now I am trying to commit my spleated commit. Success was only for the 
first part. As I told, I am trying to understand why the second piece 
was not propagated. Hope soon I will do it and return to numerous Cling 
error messages.
Victor

**Review by klendathu2k — COMMENTED** [review]
The request is to merge 29 commits, changing 248 files, into the Star6 branch of the main STAR repository:

https://github.com/star-bnl/star-sw/tree/Star6

The branch you are merging into is 76 commits _behind_ the main branch of the STAR repository.  Who is keeping this branch up to date with changes to main?  Eventually want to merge ROOT6 development into main.  But if this branch continues to lag behind... I'm not sure that we are getting closer to that goal.

**Comment by klendathu2k** [comment]
As soon as I see 248 files being changed... reviewing this request goes way down to the bottom of my TODO list. 

My recommendation is to create a new branch off of main in your repository.  Every day you need to fetch changes from the main repository, so that it stays in sync with main.  On that branch, make your root 6 changes.  Make a *small* number of changes that fix one single issue, and commit them back to the main repository.  Repeat until done.

**Review by PhilippWeidenkaff — APPROVED** [review]
Approved from my side.

**Comment by perevbnlgov** [comment]
Pull request closed , no merge.

**Pull request closed without merging**
