### PR TITLE
[ci] Include StRoot/StEEmcPool into CI build

### PR DESCRIPTION
**Pull request by plexoos**
Don't remember the reason why it was excluded from the build but I think it should compile now. Let's see..

### CODE REVIEW

**Comment by plexoos** [comment]
Any objections, Kolja? @kkauder

**Review by veprbl — APPROVED** [review]
Looks fine, although I didn't review the "Address compiler warning about set but not used variables".

**Comment by plexoos** [comment]
The effect from addressing the compiler warnings can be verified to some extent by diffing the log files

**Comment by veprbl** [comment]
A strange error in CI:
```
#21 1408.0 In file included from .sl88_gcc789/OBJ/StRoot/StFgtPool/StFgtPedMaker/StFgtPedMaker_Cint.cxx:40:0:
12139
#21 1408.0 .sl88_gcc789/OBJ/StRoot/StFgtPool/StFgtPedMaker/StFgtPedMaker.h: In function 'void ROOT::destruct_vectorlEStFgtPedMakercLcLpedData_tgR(void*)':
12140
#21 1408.0 .sl88_gcc789/OBJ/StRoot/StFgtPool/StFgtPedMaker/StFgtPedMaker.h:86:11: error: 'struct StFgtPedMaker::pedData_t' is protected
12141
#21 1408.0     struct pedData_t {
12142
#21 1408.0            ^
12143
#21 1408.0 .sl88_gcc789/OBJ/StRoot/StFgtPool/StFgtPedMaker/StFgtPedMaker_Cint.cxx:530:15: error: within this context
12144
#21 1408.0        typedef vector<StFgtPedMaker::pedData_t> current_t;
12145
#21 1408.0                ^
12146
#21 1408.1 cons: *** [.sl88_gcc789/OBJ/StRoot/StFgtPool/StFgtPedMaker/StFgtPedMaker_Cint.o] Error 1
12147
#21 1408.1 cons: errors constructing .sl88_gcc789/OBJ/StRoot/StFgtPool/StFgtPedMaker/StFgtPedMaker_Cint.o
```

**Comment by plexoos** [comment]
I made a mistake in #86 by not including StFgtPool into ROOT6 build
The error looks similar to this https://github.com/star-bnl/star-sw/pull/6/commits/9bce66cfe89a6f3cc69b449547726e9b1d32b516 fix. I think in ROOT6 when creating dictionaries for persistent classes they don't do `#define private public` anymore...

**Comment by plexoos** [comment]
Here is how we can verify that 8b784b7b79ece0daaf016035733f5b4e09ad75b5 worked:

```shell
export GH_USER=<username>
export GH_TOKEN=<yourtoken>
curl -L -s -u "$GH_USER:$GH_TOKEN"  https://api.github.com/repos/star-bnl/star-sw/actions/jobs/3297404823/logs | grep ' #21 [0-9]' |  awk '!($1=$2=$3="")' > log_before
curl -L -s -u "$GH_USER:$GH_TOKEN"  https://api.github.com/repos/star-bnl/star-sw/actions/jobs/3296600017/logs | grep ' #20 [0-9]' |  awk '!($1=$2=$3="")' > log_after
diff -U0 log_before log_after
```

```diff
--- log_before	2021-08-11 13:53:01.000000000 -0400
+++ log_after	2021-08-11 13:52:54.000000000 -0400
@@ -8608,4 +8607,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcClusterMaker/StEEmcClusterMaker.cxx: In member function 'virtual Bool_t StEEmcClusterMaker::buildSmdClusters()':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcClusterMaker/StEEmcClusterMaker.cxx:340:10: warning: variable 'energy' set but not used [-Wunused-but-set-variable]
-   Float_t energy[288]; for ( Int_t i=0; i<288; i++ ) energy[i]=0.;
-   ^
@@ -8644,4 +8639,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcDataDrivenMcMaker/StEEmcDataDrivenMcMaker.cxx: In member function 'void StEEmcDataDrivenMcMaker::processTrack(StMcTrack*)':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcDataDrivenMcMaker/StEEmcDataDrivenMcMaker.cxx:261:25: warning: variable 'maxHits' set but not used [-Wunused-but-set-variable]
-   StMcCalorimeterHit* maxHits[2];
-   ^
@@ -8766,4 +8757,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcIUPi0/StEEmcIUClusterMaker.cxx: In member function 'Bool_t StEEmcIUClusterMaker::buildSmdClusters()':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcIUPi0/StEEmcIUClusterMaker.cxx:385:10: warning: variable 'energy' set but not used [-Wunused-but-set-variable]
-   Float_t energy[288]; for ( Int_t i=0; i<288; i++ ) energy[i]=0.;
-   ^
@@ -8772,4 +8759,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcIUPi0/StEEmcIUMixMaker.cxx: In member function 'void StEEmcIUMixMaker::mixReal()':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcIUPi0/StEEmcIUMixMaker.cxx:144:11: warning: variable 'imax' set but not used [-Wunused-but-set-variable]
-   Int_t imax=0;
-   ^
@@ -8781,7 +8764,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcIUPi0/StEEmcIUPointMaker.cxx: In member function 'Bool_t StEEmcIUPointMaker::findPoints(Int_t, StEEmcIUSmdClusterVec_t, StEEmcIUSmdClusterVec_t, StEEmcIUPointVec_t&)':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcIUPi0/StEEmcIUPointMaker.cxx:320:10: warning: variable 'go' set but not used [-Wunused-but-set-variable]
-   Bool_t go = false;
-   ^
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcIUPi0/StEEmcIUPointMaker.cxx:650:7: warning: variable 'imin2' set but not used [-Wunused-but-set-variable]
-   int imin2=-1,inn=-1;
-   ^
@@ -8828,4 +8804,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcPi0Mixer/StEEmcMixMaker.cxx: In member function 'void StEEmcMixMaker::mixReal()':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcPi0Mixer/StEEmcMixMaker.cxx:139:11: warning: variable 'imax' set but not used [-Wunused-but-set-variable]
-   Int_t imax=0;
-   ^
@@ -8855,7 +8827,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcPointMaker/StEEmcPointFitMaker.cxx: In member function 'Int_t StEEmcPointFitMaker::FitSector(Int_t)':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcPointMaker/StEEmcPointFitMaker.cxx:160:14: warning: variable 'resu' set but not used [-Wunused-but-set-variable]
-   Double_t resu=0.;
-   ^
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcPointMaker/StEEmcPointFitMaker.cxx:161:14: warning: variable 'resv' set but not used [-Wunused-but-set-variable]
-   Double_t resv=0.;
-   ^
@@ -8863,4 +8828,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcPointMaker/StEEmcPointMaker.cxx: In member function 'Bool_t StEEmcPointMaker::findPoints(Int_t, StEEmcSmdClusterVec_t, StEEmcSmdClusterVec_t, StEEmcPointVec_t&)':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcPointMaker/StEEmcPointMaker.cxx:304:10: warning: variable 'go' set but not used [-Wunused-but-set-variable]
-   Bool_t go = false;
-   ^
@@ -8868,7 +8829,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcPointMaker/StMyPointMaker.cxx: In member function 'Bool_t StMyPointMaker::split(const StEEmcSmdCluster&, const StEEmcSmdCluster&, StEEmcSmdCluster&, StEEmcSmdCluster&, Float_t&)':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcPointMaker/StMyPointMaker.cxx:522:11: warning: variable 'weight1' set but not used [-Wunused-but-set-variable]
-   Float_t weight1[288]; for ( Int_t ii=0;ii<288;ii++ ) weight1[ii]=0.;
-   ^
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcPointMaker/StMyPointMaker.cxx:523:11: warning: variable 'weight2' set but not used [-Wunused-but-set-variable]
-   Float_t weight2[288]; for ( Int_t ii=0;ii<288;ii++ ) weight2[ii]=0.;
-   ^
@@ -8978,3 +8932,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/FgtSandbox1/StFgtSlowSimuMaker.cxx:262:11: warning: unused variable 'numbv2' [-Wunused-variable]
-   Int_t numbv2 = (ivid/10000)%100;
-   ^
@@ -9156,14 +9107,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/LCP/CtbMatching.cxx: In member function 'void CtbMatching::ctb_get_slat_from_data(int, int, double&, double&)':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/LCP/CtbMatching.cxx:62:16: warning: variable 'eta' set but not used [-Wunused-but-set-variable]
-   double phi,eta ;
-   ^
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/LCP/CtbMatching.cxx: In member function 'unsigned int CtbMatching::match(const StMuTrack*)':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/LCP/CtbMatching.cxx:89:9: warning: variable 'shouldHit' set but not used [-Wunused-but-set-variable]
-   bool shouldHit;
-   ^
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/LCP/CtbMatching.cxx:90:11: warning: variable 'trackEtaInCTBFrame' set but not used [-Wunused-but-set-variable]
-   double trackEtaInCTBFrame;
-   ^
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/LCP/CtbMatching.cxx:91:11: warning: variable 'trackPhiInCTBFrame' set but not used [-Wunused-but-set-variable]
-   double trackPhiInCTBFrame;
-   ^
@@ -9229,4 +9166,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/muEztPanitkin/SpyCopyCat.cxx: In member function 'void SpyCopyCat::accumulate(EztEmcRawData*, EztEmcRawData*)':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/muEztPanitkin/SpyCopyCat.cxx:41:7: warning: variable 'crateID' set but not used [-Wunused-but-set-variable]
-   int crateID=0;
-   ^
@@ -9269,4 +9202,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcStatus/oflPedStat.cxx: In member function 'int oflPedStat::procDetector(char*, float, float, float, float, float, int)':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StEEmcStatus/oflPedStat.cxx:87:40: warning: variable 'chan' set but not used [-Wunused-but-set-variable]
-   char title[100],crate[4],txt[3]; int chan=-1;
-   ^
@@ -12404,12 +12333,0 @@
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StMaxStripPi0/StEEmcClusterMaker.cxx: In member function 'Bool_t StEEmcClusterMaker::buildSmdClusters()':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StMaxStripPi0/StEEmcClusterMaker.cxx:297:10: warning: variable 'energy' set but not used [-Wunused-but-set-variable]
-   Float_t energy[288]; for ( Int_t i=0; i<288; i++ ) energy[i]=0.;
-   ^
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StMaxStripPi0/StEEmcMixMaker.cxx: In member function 'void StEEmcMixMaker::mixReal()':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StMaxStripPi0/StEEmcMixMaker.cxx:114:11: warning: variable 'imax' set but not used [-Wunused-but-set-variable]
-   Int_t imax=0;
-   ^
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StMaxStripPi0/StEEmcPointMaker.cxx: In member function 'Bool_t StEEmcPointMaker::findPoints(Int_t, StEEmcSmdClusterVec_t, StEEmcSmdClusterVec_t, StEEmcPointVec_t&)':
-   .sl88_gcc789/OBJ/StRoot/StEEmcPool/StMaxStripPi0/StEEmcPointMaker.cxx:256:10: warning: variable 'go' set but not used [-Wunused-but-set-variable]
-   Bool_t go = false;
-   ^
```

**Pull request merged**
