### PR TITLE
[SL19b] Backport PRs with fixes for simulation/embedding jobs

### PR DESCRIPTION
**Pull request by plexoos**

### CODE REVIEW

**Comment by starsdong** [comment]
Dmitri, I see you merged the requests for other libraries. Any concern for this one? Thanks

**Comment by plexoos** [comment]
According to this message https://lists.bnl.gov/mailman/private/star-scmgt-l/2021-December/000416.html we expect another update from @zhux97

**Comment by plexoos** [comment]
As confirmed by Xianglei during the S&C meeting we can merge this now and update SL19b later if necessary.

**Comment by plexoos** [comment]
@genevb You should be able to build the libraries on the farm from tag SL19b_3. It is available now

**Comment by genevb** [comment]
Sl19b is rebuilt using the SL19b_3 tag. Thanks,
-Gene

**Pull request merged**
