### PR TITLE
Assorted updates to StRoot/RTS, including "char *" issue

### PR DESCRIPTION
**Pull request by jml985**
This updates the StRoot/RTS directories to solve issues with the conversion between char * and const char *

### CODE REVIEW

**Comment by plexoos** [comment]
Is this ready? @akioogawa

**Review by akioogawa — APPROVED** [review]

**Comment by plexoos** [comment]
@tonko-lj ?

**Comment by jml985** [comment]
Yes I think it is ready as far as we are concerned, though I don't have the metrics you were using.  If there are still issues let me know.

**Comment by plexoos** [comment]
The metric is just the warnings you find when you build

**Comment by jml985** [comment]
Right, but we don't build the way you do.   What we did was set the compiler to treat warnings as errors, then compile our code.   We had to exclude many of these, such as "unused function" warnings, which make no sense in code that is effectively libraries...   The CI seemed to go through correctly.   I thought you showed some plots of the number of various warnings and those are the metrics I meant.

**Comment by plexoos** [comment]
> Right, but we don't build the way you do. What we did was set the compiler to treat warnings as errors, then compile our code.

Treating warnings as errors is exactly what we would like to do after we clean up the existing code. We haven't switch to that mode yet.

> We had to exclude many of these, such as "unused function" warnings, which make no sense in code that is effectively libraries... 

I saw such warnings in your code. They make sense because the functions are defined as static and that prevents them from being accessed (by name) in any compilation unit other than where they are defined. Here is an example with the static `t_delta` function that is not used in the same compilation unit: https://github.com/star-bnl/star-sw/blob/main/StRoot/RTS/src/DAQ_FGT/fstPed.cxx#L31

Unless there is a really good reason we should not ignore any from -Wall and perhaps -Wextra

> The CI seemed to go through correctly. I thought you showed some plots of the number of various warnings and those are the metrics I meant.

The plots just show the count of warnings to keep track of the progress. I did not split by the module but I can produce one specifically for StRoot/RTS/
To search the logs for warnings you can go to the "Checks" tab on the PR page, pick a job (e.g. "build (root5, gcc485)") and download the log by selecting from the menu:
  
Screen Shot 2022-09-28 at 3 01 41 PM

**Comment by plexoos** [comment]
Here are the counts specifically for this PR #406 (as of 0951ee3f36c4d86185d4d9336c6e8387dfeb8af1) and StRoot/RTS module compared to the same in SL22c

fix_warns

```
 msg_id                                                                    msg
      0        deprecated conversion from string constant to [-Wwrite-strings]
      1                  variable set but not used [-Wunused-but-set-variable]
      2                                    unused variable [-Wunused-variable]
      3                               defined but not used [-Wunused-function]
      4     may be used uninitialized in this function [-Wmaybe-uninitialized]
      5                               statement has no effect [-Wunused-value]
      6                            value computed is not used [-Wunused-value]
      7 iteration invokes undefined behavior [-Waggressive-loop-optimizations]
      8     format expects argument of type, but argument has type [-Wformat=]
      9                               defined but not used [-Wunused-variable]
     10           extra tokens at end of #endif directive [enabled by default]
     11                            label defined but not used [-Wunused-label]
     12                                         redefined [enabled by default]
```

Looks like an improvement but still more to be fixed.
I'll just bring everyone's attention again to the fact that a good deal of these is already addressed in #389 and #395

**Pull request merged**
