### PR TITLE
Adding StTriggerData2022 for new v47 trigger data structure

### PR DESCRIPTION
**Pull request by akioogawa**
Adding StTriggerData2022 to StEvent for new v47 trigger data structure, and associated changes in StDAQLib and StTriggerDataMaker

### CODE REVIEW

**Review by ullrich-bnl — APPROVED** [review]

**Comment by akioogawa** [comment]
@klendathu2k can you review this? We need this for online monitoring (and fast offline and many more) very soon as run22 starts.

**Comment by klendathu2k** [comment]
I'll take a look shortly, but there's a cost ;)

Could you look at PR#176? https://github.com/star-bnl/star-sw/pull/176

We need that for an embedding request (and you're a codeowner on 
pams/sim).

**Review by klendathu2k — CHANGES_REQUESTED** [review]
I don't see any obvious issues.   Let's merge.

**Review by klendathu2k — APPROVED** [review]
... meant to click approve... let's merge.

**Pull request merged**
