### PR TITLE
[ci] Include StRoot/StFgtPool into CI build

### PR DESCRIPTION
**Pull request by plexoos**

### CODE REVIEW

**Review by veprbl — APPROVED** [review]
Nice

**Comment by plexoos** [comment]
You should have waited for ROOT6 to finish 😸 It can end up like #83

**Comment by veprbl** [comment]
Well, CI failures are not end of the world :)
My main thought was that an StMaker has no business with curses, so it's nice that you've caught this.

**Comment by plexoos** [comment]
Merge this trivial fix as there are no designated code owners for StRoot/StFgtPool

**Pull request merged**
