### PR TITLE
Update README.MC

### PR DESCRIPTION
**Pull request by akioogawa**
First pull request to try out!

### CODE REVIEW

**Review by plexoos — APPROVED** [review]
This code is not used in production so, no problem merging it from my side.

**Comment by akioogawa** [comment]
Sorry about adding files under StarGenerator/FILT in this RP. Add Jason as a reviewer for those?

**Comment by plexoos** [comment]
Added @klendathu2k as owner of /StRoot/StarGenerator See #10

**Comment by plexoos** [comment]
Replaced by #16

**Pull request closed without merging**
