### PR TITLE
Vpd start mode integrated

### PR DESCRIPTION
**Pull request by DanielTorres98**
# Description
 StBTofCalibMaker::tofCellResolution function can now use VPD start resolution if UseVpdStart is set to TRUE. 
 Additionally, singleTubeRes was fixed to compute the VPD resolution correctly based on which tubes were used.

### CODE REVIEW

**Comment by fgeurts** [comment]
Please check error in compilation:

'class StVpdSimConfig' has no member named 'singleTGubeRes'
204.2          start_resolution = mVpdResConfig->singleTGubeRes(mVPDHitPatternEast, mVPDHitPatternWest)/1000.;

**Comment by Morning-Ye** [comment]
looks good to me

**Comment by fgeurts** [comment]
Thanks for addressing my earlier comment.

**Comment by fgeurts** [comment]
You need to update the branch which appears to be out-of-date with the base branch

**Review by fgeurts — APPROVED** [review]

**Review by Morning-Ye — APPROVED** [review]
looks good

**Pull request merged**
