### PR TITLE
Corrections from TFG for dEdx AuAu200_2019

### PR DESCRIPTION
**Pull request by fisyak**
The update introduces an additional correction for dE/dx handled by a new table identified by `StTpcdEdxCorrection::kzCorrectionC` which is currently activated only for the Run 19 AuAu200 data. The authors claim that the change won't affect any other dataset. A slide illustrating the related problem is available at https://drupal.star.bnl.gov/STAR/event/2022/03/09/SC-Management-Meeting/Run19-AuAu200-Calibration-Status

The change in `StRoot/StDetectorDbMaker` looks pretty safe as it only adds a diagnostic routine `St_TpcAvgPowerSupplyC::PrintC()`

### CODE REVIEW

**Comment by genevb** [comment]
Just a note that this would need to be included in SL22a to produce the Run 19 AuAu200 data.

**Comment by plexoos** [comment]
I don't see anything constraining these changes to the Run 19 AuAu200 data, so it looks like these changes can affect other samples too. Should we just trust that this is an improvement?

**Review by dmarkh — APPROVED** [review]

**Review by iraklic — APPROVED** [review]

**Comment by plexoos** [comment]
> Just a note that this would need to be included in SL22a to produce the Run 19 AuAu200 data.

Gene, from your comment I conclude that you know the reason for these changes in the dEdx calculation. Perhaps this was discussed in a TPC meeting. Can you please update the description in the top post with some details before someone merges it?

**Comment by genevb** [comment]
What I know...

1. Yuri said at the past two TPC meetings that (unspecified) code changes were needed for the dEdx in 2019 AuAu200. I know no other details about the code changes, nor what issue they address in 2019 AuAu200, nor what other impacts there may be (such as for other datasets, as asked).
2. Yuri's title for this PR mentions "dEdx AuAu200_2019"
3. Code changes imply a new library. We want to freeze SL22a very soon, so SL22a would be the library these codes go into.

-Gene

**Comment by plexoos** [comment]
I updated the PR's description with some details mentioned at the meeting. Feel free to edit and include more details in the log message when merging.

**Comment by starsdong** [comment]
PR 319 includes the commit requested here (description in PR 319 updated as well).
PR 319 has been merged. I am going to close this one.

**Pull request closed without merging**
