### PR TITLE
Star6 add new fils

### PR DESCRIPTION
**Pull request by perevbnlgov**
New main::files copied to Star6. Technical PR. No need to check

### CODE REVIEW

**Comment by klendathu2k** [comment]
There's something like 166 files to check here.  I think this is a waste 
of effort.
You are doing something *by hand* that git will do for you 
automatically, if you
setup your repository correctly.

You should fork star-sw  (which you have).

On that repository, you should create a branch off of main for ROOT6 
development.

Keep *your* version of main in sync with star-sw/main by pulling changes 
periodically.

Keep your development ROOT6 up to date with *your* main, but 
periodically pulling / merging.

None of that requires a review, until you are ready to add new codes 
back into star-sw/main
from your development branch.


Instead, you are spending your time finding differences between 
star-sw/Star6 and star-sw/main.
And doing pull requests that require reviews.  Because "your" 
development branch is part of the
main repository.

-------

... that said, I'll have a look and approve later today or tomorrow.

**Comment by perevbnlgov** [comment]
Hi Jason,
the case is not so simple.
1. Fork created my "origin" with "main" and "Star6"
2. Fetch command can merge
    upstream::maim ==> origin::main and
    upstream::Star6 ==> origin::Star6
    but when i delete origin::Star6 and create it again, then 
immediately:
    upstream::main ==> origin::Star6
    So GitHub knows better what to do than me. No flexibility is allowed.
3. When you and Dmitry did update (Table and his version of sstrean) you 
update
    main. I dd not found how to put yours corrections from main to 
origin::Star6

You propose me to do modifications in upstream::Star6 and then move it 
origin::main.
And keep origin::Star6 untouched. It is also very weird.

My way also is ugly enough but I did not found how to cheat GitHub more 
elegant :
1. Create branch local::Star6_Number with updates;
2. Push to origin::Star6_Number
3. PR it into upstream::Star6
4. Then upstream::Star6 ==> origin::Star6

It is hundred times more complicated than CVS, but it is new fascion.
Maybe you know the better way.
Victor

**Comment by klendathu2k** [comment]
Victor--

> I dd not found how to put yours corrections from main to
> origin::Star6

And that is the problem.  You are trying to work with origin:Star6, 
which you
do not own.  Instead, you should be working with branches that are on 
your repository
until you are ready to commit your changes to the main repository:


Start with your fork of star-sw.

When you make a change,  create a branch of main on your fork.  Work, 
commit
code to that fork, and when you are ready to integrate back into the 
main repository,
you do four simple things.

1) Pull changes on star-sw onto your copy of the main branch.... this 
gives you
access to everyone's changes so that you can merger them with your own.

This is literally one command (git pull) under your control.

2) Then you merge those changes with your development branch.

3) After merging (and resolving any possible conflicts) push your 
development branch
to github.

4) Then open a pull request between my branch and star-sw/main.

Cheers,
Jason

**Comment by perevbnlgov** [comment]
Hi Jason,
I wrote you answer, but I did something wrong, and I lost it.
I am writing again.

Your proposed way how to handle Star6 updating is not working for me.
Starting from CVS era all Root6 updates are contains in separate branch
Star6. Only when this branch will be complete and fully tested, it will 
be
moved into main. This decision was taken years ago. To place Root6 
correction
directly into the main branch is too dangerous. In your example you 
directly
put correction into "main". I know to keep separate branch in GitHub is 
not so easy
as in CVS, but we have no choice. The main problem is to put updates 
from the "main"
to "Star6". Yeas there are many of them. But there is no need to check 
them all,
they are already uproved. Even more, in my opinion there is no sense for 
a few peoples
to uprove each sneeze in not the "main" branch. It is huge wasting of 
time. about My work
with GitHub now is about 100 times slower than in CVS. Sometimes I am 
waiting approval
many months. For example:

perevbnlgov:Star6_addTable.332  // StRoot/Table approved only by Akio
perevbnlgov:Star6_addNewFils.333// NOT Approved
perevbnlgov:Star6_mainRTS.331   // Approved only by Akio
perevbnlgov:Star6.330           // Approved

All of this is just technical updates , only main==>Star6. No need to 
approve at all
Two weeks waiting. Some updates were waiting from august, and I cancel 
them.

So I think our GitHub policy should be changed. At least approval for 
NON "main"
branch it is better to abbolish

Victor

**Comment by starsdong** [comment]
Hi Victor and Jason,

These are good discussions in order to clear things up. I see there is a difference between the proposals you two brought up. Jason suggested to create the development branch from your fork and request PR to origin/main directly while Victor is trying to set up the origin/Star6 branch and try to sync local development with origin/Star6. Maybe other experts (Dmitri or Gene) can add more comments on which one will be better for review/evaluation? Thanks

**Comment by perevbnlgov** [comment]
Xin, I already have
upstream:Star6 and origin:Star6
In upstream:Star6 everybody can add updates via PR and in origin::Star6 
only me. It is a fork. As I understand I am doing exactly according 
GitHub documentation, as a understand it. As I see, only me, who is 
using separate brunch version in GitHub.
Victor

**Comment by perevbnlgov** [comment]
Hi Jason,
sorry for delay.
I understand your proposal, but, as usual BUT.
When I started to work with Root6, the demand was to create a branch.
This allows development safe, without destroying the official version.
I think it is reasonable. So I created branch in CVS, and start to work.
Then CVS was changed to GitHub. Immediately araised of problems.
Your solution is working without separate branch Star6. It is not safe 
at all.
After my investigation of GitHub, I found that github is not supposed to 
work
with separate branch at all. Git itself can. GitHub is not flexible 
system with
the set of mysterious  limitations. Example:
I can fetch upstream::main ==> origin::main
I can fetch upstream::Star6 ==> origin::Star6
I can NOT fetch upstream::main ==> origin::Star6
Why? Because!
Git itself is over complicated but flexible enough.
Now I am trying still to use separate branch Star6. It is possible but 
not easy
But when CVS is gone, we should forget word "easy"
Victor

**Pull request closed without merging**
