### PR TITLE
Eliminte HitFilt from production chains aas obsolete

### PR DESCRIPTION
**Pull request by fisyak**
By Frank request create a separate request for eliminate obsolete option HitFilt from production chains.

### CODE REVIEW

**Review by klendathu2k — APPROVED** [review]
I note that the KeepSvtHit option is removed as well, presumably b/c it only makes sense when the hitfilt option is in place.  I don't see any issues here.

**Review by genevb — COMMENTED** [review]
I maintain that it's inappropriate to change old chains, as our practice has been to create new versions of old chains (e.g. increment a letter at the end of the chain name) when we modify them. The changes in this PR are nevertheless rather inconsequential, and the old chains are on record if they need resurrected, so I will not block this if it allows the Collaboration to move forward in other ways.

I also appreciate that this change was, appropriately, isolated in its own pull request.

**Review by iraklic — APPROVED** [review]

**Comment by iraklic** [comment]
I understand Gene's point, but just to add my two cents, I multiple times forgot to explicitly turn off hitfilt  and have run reco without a desired output, this would have saved me a lot of time :)

**Comment by plexoos** [comment]
Can someone explain how this option is obsolete if it is a dependent option in so many chains, e.g. `pp2024a`?

**Pull request merged**
