### PR TITLE
[SL21c] Add Anti-H4 Lambda decay to Anti-He4 + pion- 

### PR DESCRIPTION
**Pull request by klendathu2k**
Update to SL21c codes for Run19 AuAu19 embedding.    [PR#176 did the same for SL20c.]

* Add H3LambdaBar decay to gstar library

* Add H4LambdaBar, He4LambdaBar & He5LambdaBar hypernuclei to StarClassLibrary.
Add only H4LambdaBar to the particle table (others are placeholders assuming
a request is made at some point).

(cherry picked from commit c109e4f41158956e72663d5fd00988cd6603e1b0)

### CODE REVIEW

**Review by genevb — APPROVED** [review]
This is identical to PR #176 , just that the target is SL21c instead of main. Fine with me if there are no other dependencies needed.

**Comment by genevb** [comment]
> This is identical to PR #176 , just that the target is SL21c instead of main.

SL21c also needs updated with #184 at some point. Seems like PRs for the same code into a tag is a bit overkill in my opinion, but whatever works...

-Gene

**Review by starsdong — CHANGES_REQUESTED** [review]
The He5L and He5Lbar hypernuclei should have the charge of +/- 2, instead of +/- 3.

**Review by starsdong — APPROVED** [review]

**Comment by klendathu2k** [comment]
> The He5L and He5Lbar hypernuclei should have the charge of +/- 2, instead of +/- 3.

Just a note.  Change to StarClassLibrary was made, which updates codes used in QA.  The definition used in starsim (pams/sim/gstar/gstar_part.g) is correct.

**Comment by klendathu2k** [comment]
@ullrich-bnl @fgeurts PR#208 needs your approval before it can be merged.

**Review by fgeurts — APPROVED** [review]
Ok. No comments

**Review by ullrich-bnl — COMMENTED** [review]
OK

**Pull request merged**
