### PR TITLE
Add K*(892)+ and K*(892)- to gstar_part.g

### PR DESCRIPTION
**Pull request by klendathu2k**
Update gstar_part.g per [embedding request](https://drupal.star.bnl.gov/STAR/starsimrequests/2022/Jan/12/charged-K-embedding-isobar).

[PDG IDs](https://pdg.lbl.gov/2021/reviews/rpp2020-rev-monte-carlo-numbering.pdf) are +/- 323.

[K*(892) PDG listing](https://pdg.lbl.gov/2021/listings/rpp2021-list-K-star-892.pdf)

### CODE REVIEW

**Comment by genevb** [comment]
And to how many libraries for embedding must this be added?
-Gene

**Comment by klendathu2k** [comment]
I believe there will be a request to add this (and a few other updates) 
to SL20c.

**Comment by zhux97** [comment]
Yes, so far we only have K*+- requests in Isobar data. So SL20c should be updated.

**Review by plexoos — APPROVED** [review]
The change looks concise. Just for my curiosity, is the width estimated somehow from the official PDG numbers?

**Comment by Hegerover** [comment]
Mam problem z prihlasenim do svojho učtu (facebook lite) neda sa obnovit, neviem heslo ani e-mail. Telefonne čislo nefungije.. Viete mi poradit?

Získajte Outlook pre Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by klendathu2k** [comment]
Yes, width is derived from the PDG values.

**Review by starsdong — APPROVED** [review]

**Comment by starsdong** [comment]
Need approval from Akio to enable the green button. Or I think Dmitri we can merge this in now. The change is straightforward.

**Comment by plexoos** [comment]
Akio usually responds quickly... So, pinging @akioogawa once again

**Comment by starsdong** [comment]
Dmitri, Akio may be busy with the run. The change is straightforward, please go ahead merge this. Thanks

**Pull request merged**
