### PR TITLE
Delete warinings BTofSimMaker.cxx

### PR DESCRIPTION
**Pull request by DanielTorres98**
This branch is to address mentioned here: [Issue 149](https://github.com/star-bnl/star-sw/issues/149)

### CODE REVIEW

**Comment by plexoos** [comment]
Thank you Daniel for addressing the warnings in StBTofSimMaker! As a formal test and to confirm that all is as expected, I am removing it from the list of packages with skipped warnings-as-errors checks.

**Review by klendathu2k — APPROVED** [review]
Looks like these changes just make sure everything is initialized, and removes unused variables.  Compilation should be sufficient test that this is correct.

**Review by genevb — COMMENTED** [review]
No objection to the `mgr/` change from me.

**Review by plexoos — APPROVED** [review]
The build logs look clean now with respect to warnings in StBTofSimMaker

**Pull request merged**
