### PR TITLE
Enable shared linking of mysqlclient lib to root4stat

### PR DESCRIPTION
**Pull request by plexoos**
An alternative solution to the issue described in PR #343

### CODE REVIEW

**Comment by plexoos** [comment]
Probably I should have sent a reminder earlier... but let's merge and see if the nightly build and tests on the farm can digest this change. If not we'll roll back.

**Comment by plexoos** [comment]
@amolhj I don't see anything wrong with the nightly tests after this merge. If you see otherwise please let me know

**Comment by genevb** [comment]
This is a minor observation that requires no action, but just to document what I observed: This PR appears to have added ~4.5 MB of memory usage to all nightly test jobs after the 2022-05-11 AutoBuild of DEV.

**Comment by plexoos** [comment]
Another observation is that the root4star executable size (on /afs) reduced from 33 MB to 31 MB. It is peculiar that root4star's size is 19 MB in the container.

There seems to be another small increase after 2022-05-16

The large step on or after 2022-03-06 seems to correspond to the changes in #314

**Pull request merged**
