### PR TITLE
Fix find_vertex.C to make ROOT interpreter happy

### PR DESCRIPTION
**Pull request by plexoos**
Based on #374 head (7c738631ec979e149fa6990420e4520780e3249c)

### CODE REVIEW

**Comment by plexoos** [comment]
Ok, fine. But what is the magic behind `<StIOMaker::Finish> IO:` vs `<StIOMaker::Finish> StIO:`

**Comment by veprbl** [comment]
> Ok, fine. But what is the magic behind `<StIOMaker::Finish> IO:` vs `<StIOMaker::Finish> StIO:`

https://github.com/star-bnl/star-sw/blob/5a762161b9600a52a6f360c9e792aaa7891ef002/StRoot/StIOMaker/StIOMaker.h#L18
https://github.com/star-bnl/star-sw/blob/5bb90874e57177c7c14d26a4bd8a1581fe503b68/StRoot/macros/analysis/find_vertex.C#L140
https://github.com/star-bnl/star-sw/blob/5bb90874e57177c7c14d26a4bd8a1581fe503b68/StRoot/macros/analysis/doEvents.C#L202

**Comment by plexoos** [comment]
This fix will be included in #374

**Comment by veprbl** [comment]
I'd simply change it to `StIOMaker("StIO"` for the fix. It's a bit annoying that makers appear with varying names in some chains for no reason.

**Comment by plexoos** [comment]
It is absolutely fine by me. Please, by all means, go ahead and make changes as you see fit, just don't make us regret we resurrect macros nobody uses or maintains 😃

**Comment by veprbl** [comment]
Okay, okay :)

**Pull request closed without merging**
