### PR TITLE
Assorted updates in OnlTools/Jevp for 2023 run

### PR DESCRIPTION
**Pull request by jml985**
These are the final updates to the JevpPlots during run 2022, some never made it into the official repository

### CODE REVIEW

**Comment by genevb** [comment]
I'm confused why there are PWGTools changes in this PR. Is this accidental?

**Comment by plexoos** [comment]
> I'm confused why there are PWGTools changes in this PR. Is this accidental?

Yes, should be fixed now

**Review by plexoos — APPROVED** [review]
Just let me know when it is ready and we'll merge

**Comment by starsdong** [comment]
I have no issue with this. Ready to merge. Thanks, Jeff and Dmitri.

**Comment by plexoos** [comment]
It compiles and does not crash the tests, can't ask for more :)

**Pull request merged**
