### PR TITLE
Backport patches for embedding

### PR DESCRIPTION
**Pull request by zhux97**
* All codes in PR #466 are included, to fix the offline cluster finder (PRs #417 and #429), update TpcRS parameter for Run19 (PR #463).
* Codes in PR #281 are included, to fix the gating grid simulation and to fix the StMcEventMaker for iTPC simulation.

These patches are needed for SL21d based embedding productions (Run18 Isobar st_hf/st_upc, Run19 FXT, Run20 FXT runs).

### CODE REVIEW

**Comment by zhux97** [comment]
Please find some slides about this PR in
https://drupal.star.bnl.gov/STAR/system/files/embedding_status_20230207_PR493.pdf

**Comment by plexoos** [comment]
Thank you Xianglei for providing the detailed explanation and the references as always. #494 contains a few technical updates for CI and adds some more tests from the SL23a_0 release. Once it is done, I'll merge this PR and let the production team know about a new SL21d release

**Review by iraklic — APPROVED** [review]
Sorry for delay. Took me a while to go over all the changes. Packing them together like this makes it a harder process to review.

**Review by plexoos — APPROVED** [review]

**Comment by genevb** [comment]
I see that SL21d_3 has been tagged with this PR included. I will proceed to build this on CVMFS today, but I would appreciate confirmation from @zhux97 that the SL21d_3 tag has everything we think we need for the embedding updates.

Thanks,
-Gene

**Comment by genevb** [comment]
Actually, there's no SL21d_3 tag for the mcgen repository yet. @plexoos , can you add that please?

**Comment by plexoos** [comment]
> can you add that please?

Yes, it's been tagged as well

**Pull request merged**
