### PR TITLE
Code ownres from the best of my knowledge

### PR DESCRIPTION
**Pull request by yfisyak**

### CODE REVIEW

**Comment by yfisyak** [comment]
Update code owners from the best my knowledge

**Review by plexoos — CHANGES_REQUESTED** [review]
The syntax of the proposed changes is wrong. Merging it here or as part of #52 will cause the entire file to be ignored.

**Comment by veprbl** [comment]
> The syntax of the proposed changes is wrong. Merging it here or as part of #52 will cause the entire file to be ignored.

Can you clarify which part is broken? Is it the maintainerless lines?

**Comment by plexoos** [comment]
Yes
> The pattern is followed by one or more GitHub usernames

**Comment by veprbl** [comment]
> Yes
> 
> > The pattern is followed by one or more GitHub usernames

Strange. That would mean that one can not remove all maintainers for a subdirectory. Should be easy to fix this PR though.

**Comment by plexoos** [comment]
I believe this PR was superseded by #60. Shall we then close this one?

**Comment by starsdong** [comment]
Dmitri, Yes. I would agree.

**Pull request closed without merging**
