### PR TITLE
ci: Add integration test for forward tracking maker

### PR DESCRIPTION
**Pull request by plexoos**
This PR merges two PR branches #396 and #397 in order to make the test possible. The test command is:

    root4star -b -q -l 'bfc.C(5, "pp2022,StiCA,BEmcChkStat,epdhit,FwdTrack", "/star/rcf/test/daq/2023/072/23072022//st_physics_23072022_raw_4000001.daq")'

The new daq file was added to the `star-test-data:v5` container https://github.com/star-bnl/star-sw/pkgs/container/star-test-data

### CODE REVIEW

**Comment by plexoos** [comment]
The new test job utilizing the "FwdTrack" option is failing supposedly due to the following error:

```
StFwdTrackMaker:ERROR - TFile::TFile : file fGeom.root does not exist
```

Issue #411 

attn @jdbrice

**Comment by jdbrice** [comment]
> The new test job utilizing the "FwdTrack" option is failing supposedly due to the following error:
> 
> ```
> StFwdTrackMaker:ERROR - TFile::TFile : file fGeom.root does not exist
> ```
> 
> Issue #411
> 
> attn @jdbrice

Forward tracking requires a ROOT geometry for GenFit. Jason and I spoke about this previously and I believe there are similar requirements for some TPC code (need for ROOT files) - we need to determine how to deal with this in production chains for FWD.

@klendathu2k you developed scripts for us to generate the GenFit ROOT geom from STAR geom tags - how can we set this up to work in production?

**Comment by jdbrice** [comment]
> This PR merges two PR branches #396 and #397 in order to make the test possible. The test command is:
> 
> ```
> root4star -b -q -l 'bfc.C(5, "pp2022,StiCA,BEmcChkStat,epdhit,FwdTrack", "/star/rcf/test/daq/2023/072/23072022//st_physics_23072022_raw_4000001.daq")'
> ```
> 
> The new daq file was added to the `star-test-data:v5` container https://github.com/star-bnl/star-sw/pkgs/container/star-test-data

Due to our recent discussion on dependency issue in #397 I dont think we should combine these PRs as it will delay #396 . It should not be needed for the chain options - can you remind me what option needs #397 and I can fix?

**Comment by plexoos** [comment]
> Due to our recent discussion on dependency issue in #397 I dont think we should combine these PRs as it will delay #396 . It should not be needed for the chain options - can you remind me what option needs #397 and I can fix?

I thought the code in #397 is used by `StFwdTrackMaker` to write the final track information into StEvent. If it is not the case then we can of course remove it from this test.

**Comment by jdbrice** [comment]
Yes you are right that #397 writes into StEvent. Maybe the better question is - what is the success condition for the test off "FwdTrack"
That option runs the StFwdTrackMaker which can run even with the old version (before implementing the write of fwd tracks to StEvent)

So if the test is simply to see if the option can run without error then in principle #397 is not needed.  Either way, if no StEvent is found then nothing will get written to StEvent.

Maybe it is better to have something more sophisticated as the success condition?

**Comment by klendathu2k** [comment]
@jdbrice The framework should automatically creates a cache file... if you access the geometry through the framework.  Which you don't b/c you load it from this fGeom.root cache file...  Chickens and eggs all over the place.  So...   you should add the following line of code to your maker...

```
/// Instantiate and cache the geometry 
GetDataBase("VmcGeometry");
```
This will (in addition to loading the geometry) create a cache file named X.geom.root.  The code snippet which creates the geometry cache filename is [here](https://github.com/star-bnl/star-sw/blob/6dd0b8e4e0317b2b82c84a9bb7bd744e414ddf85/StarDb/AgMLGeometry/CreateGeometry.h#L14).

**Comment by plexoos** [comment]
@jdbrice Daniel, did you have a chance to implement the fix suggested above by Jason? It would be nice to see that the test passes before we merge #396

**Comment by jdbrice** [comment]
@plexoos I tried to implement the suggestion by @klendathu2k mentioned above, but it does not seem to work. I was planning to implement this as part of the PR #492 to get everything in order. 

I add one line to the StFwdTrackMaker::Init() before the track fitter tries to load the geometry. However the log output I get from this is:

```sh
StChain:INFO  - VmcGeometry
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2002.C IGNORED
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2003a.C IGNORED
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2003b.C IGNORED
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2003c.C IGNORED
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2004b.C IGNORED
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2004d.C IGNORED
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2004x.C IGNORED
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2005c.C IGNORED
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2005d.C IGNORED
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2005e.C IGNORED
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2006a.C IGNORED
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2006b.C IGNORED
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2007a.C IGNORED
StFwdTrackMaker:ERROR - St_db_Maker::Time : Unrecognised File name Geometry.y2007a.C IGNORED
StFwdTrackMaker:INFO  - CreateGeometry : File y2012.h has been found as /afs/rhic.bnl.gov/star/packages/DEV/StarDb/AgiGeometry/y2012.h
StFwdTrackMaker:INFO  - TGeoManager::TGeoManager : Geometry y2012, y2012 geometry from pams/ plus fgt and idsm from AgML created
StFwdTrackMaker:INFO  - TGeoMaterial::ctor : Material AIR defined with fractional Z=7.300000
StFwdTrackMaker:INFO  - TGeoMaterial::ctor : Material PIPE_PVACUUM defined with fractional Z=7.300000
StFwdTrackMaker:INFO  - TGeoMixture::DefineElement : Mixture TPCE_AL_HONEYCOMB has element defined with fractional Z=4.500000
StFwdTrackMaker:INFO  - TGeoMaterial::ctor : Material TPCE_SENSITIVE_GAS defined with fractional Z=17.436170
StFwdTrackMaker:INFO  - TGeoMixture::DefineElement : Mixture BTOF_HONEYCOMB has element defined with fractional Z=4.500000
StFwdTrackMaker:INFO  - TGeoMaterial::ctor : Material CALB_CPOLYSTYREN defined with fractional Z=5.615385
StFwdTrackMaker:INFO  - TGeoMaterial::ctor : Material ECAL_AIR defined with fractional Z=7.300000
StFwdTrackMaker:INFO  - TGeoMaterial::ctor : Material ECAL_POLYSTYREN defined with fractional Z=5.615385
StFwdTrackMaker:INFO  - TGeoMaterial::ctor : Material ECAL_SCINT defined with fractional Z=5.615385
StFwdTrackMaker:INFO  - TGeoMaterial::ctor : Material ECAL_SMDSTRIP defined with fractional Z=5.615385
StFwdTrackMaker:INFO  - TGeoMixture::DefineElement : Mixture ECAL_EBLS has element defined with fractional Z=6.465000
StFwdTrackMaker:INFO  - TGeoMixture::DefineElement : Mixture ECAL_EBLS has element defined with fractional Z=9.549000
StFwdTrackMaker:INFO  - TGeoMixture::DefineElement : Mixture ECAL_EBLS has element defined with fractional Z=5.615000
StFwdTrackMaker:INFO  - TGeoMixture::DefineElement : Mixture ECAL_EFLS has element defined with fractional Z=9.013000
StFwdTrackMaker:INFO  - TGeoMixture::DefineElement : Mixture ECAL_EFLS has element defined with fractional Z=9.549000
StFwdTrackMaker:INFO  - TGeoMixture::DefineElement : Mixture ECAL_EFLS has element defined with fractional Z=6.465000
StFwdTrackMaker:INFO  - TGeoMaterial::ctor : Material BBCM_CPOLYSTYREN defined with fractional Z=5.615385
StFwdTrackMaker:INFO  - TGeoMaterial::ctor : Material FPDM_CPOLYSTYREN defined with fractional Z=5.615385
StFwdTrackMaker:INFO  - TGeoMaterial::ctor : Material ZCAL_SCINTILLATOR defined with fractional Z=5.615385
StFwdTrackMaker:INFO  - TGeoMixture::DefineElement : Mixture MUTD_NOMEX has element defined with fractional Z=4.500000
StFwdTrackMaker:INFO  - TGeoMaterial::ctor : Material FGTD_SENSITIVE_FGT_G defined with fractional Z=14.836000
StFwdTrackMaker:INFO  - TGeoBuilder::MakePara : parallelipiped TRI8 having alpha=0, theta=0 -> making box instead
StFwdTrackMaker:INFO  - TGeoBuilder::MakePara : parallelipiped TRI9 having alpha=0, theta=0 -> making box instead
```

and maybe most importantly, no cache file is produced - at least not according to the filename structure linked to above.

using the chain:
```
in, y2023, db, StEvent, MuDST, fcs, fst, ftt, fwdTrack
```

but any geometry (`dev2022`) give the same result.

Maybe another deep is needed before calling 

```cpp
GetDataBase("VmcGeometry");
```

**Comment by jdbrice** [comment]
OK I think it just requires 

```sh
agml usexgeom
```

in the chain to work. Anyways, the newest commit on PR #492 will resolve this according to Jasons comment above

**Comment by plexoos** [comment]
The test has been moved to #492

**Pull request closed without merging**
