### PR TITLE
Change chain option names to something more descriptively useful

### PR DESCRIPTION
**Pull request by genevb**
The chain option names introduced in PR #24 were perhaps a bit too specific, as there are situations outside of pp and pA collisions where these options are useful. These alternative chain options were agreed upon by @ZaochenYe , @BassamAboona , and Carl Gagliardi. It would have been good to get consent from @fgeurts as well, but he may not be available promptly.

It would be worth having these alternative chain options in the upcoming SL21c_v2 library tag so that we use the newer versions of the chain option names for all productions from here forward, and not have something unique to just SL21c productions.

-Gene

### CODE REVIEW

**Review by Morning-Ye — COMMENTED** [review]
Hello Gene, these changes look good to me.

**Review by Morning-Ye — APPROVED** [review]

**Comment by plexoos** [comment]
Hi Gene: `SL21c_v2` does not seem to be consistent with the naming convention used in the past. If you list the available tags since, say, 2010 the naming pattern suggests that `SL21_1` should be used for the next minor update

```
$ git tag -l SL1* SL2* | grep -vi embed
SL10a
SL10b
SL10c
SL10c_1
SL10c_2
SL10c_3
SL10c_4
SL10d
SL10e
SL10f
SL10g
SL10h
SL10h_1
SL10h_2
SL10h_3
SL10h_4
SL10h_5
SL10i
SL10i_1
SL10i_2
SL10i_3
SL10i_4
SL10j
SL10j_1
SL10j_2
SL10k
SL10k_1
SL10k_2
SL10k_3
SL10k_4
SL10k_test
SL11a
SL11b
SL11b_1
SL11b_2
SL11b_tmp
SL11c
SL11c_1
SL11c_2
SL11c_3
SL11d
SL11d_1
SL11d_2
SL11d_3
SL11e
SL11e_1
SL11e_2
SL12a
SL12a_1
SL12a_2
SL12b
SL12b_1
SL12b_2
SL12c
SL12c_1
SL12c_2
SL12d
SL12d_1
SL12d_2
SL12e
SL12e_1
SL12e_2
SL13a
SL13a_1
SL13a_2
SL13a_3
SL13b
SL13b_1
SL13b_2
SL13c
SL13c_1
SL13c_2
SL13d
SL14a
SL14a_1
SL14a_2
SL14b
SL14c
SL14d
SL14e
SL14f
SL14g
SL14g_1
SL14g_2
SL14g_3
SL14h
SL14h_1
SL14i
SL14i_1
SL14i_2
SL15a
SL15a_fix
SL15b
SL15b_1
SL15c
SL15d
SL15e
SL15f
SL15g
SL15h
SL15i
SL15j
SL15k
SL15k_1
SL15l
SL16a
SL16b
SL16b_1
SL16c
SL16d
SL16d_1
SL16e
SL16f
SL16g
SL16h
SL16i
SL16j
SL16k
SL16l
SL17a
SL17b
SL17c
SL17d
SL17e
SL17f
SL17f_1
SL17g
SL17g_1
SL17g_t202002
SL17h
SL17i
SL18a
SL18b
SL18c
SL18c_1
SL18d
SL18e
SL18f
SL18f_1
SL18g
SL18h
SL19a
SL19b
SL19b_1
SL19b_2
SL19c
SL19c_1
SL19d
SL19d_1
SL19d_2
SL19e
SL19e_1
SL20a
SL20b
SL20c
SL20d
SL21a
SL21b
SL21b_v2
SL21c
```

**Comment by genevb** [comment]
Yes, Dmitri, you are right. We have used _vN when creating embed library iterations, but just _N for standard libraries (with the exception of SL21b_v2). Thanks for catching this.
-Gene

**Review by plexoos — APPROVED** [review]
Looks good to me too

**Comment by plexoos** [comment]
@fgeurts :point_up: ❓

**Comment by fgeurts** [comment]
> @fgeurts ☝️ ❓
I have no objections to introducing these chain options.
I don't care too much about the precise labeling of the options but frankly find the current choice somewhat overly descriptive. Still, nothing that should keep the introduction of these labels from moving forward.

**Pull request merged**
