### PR TITLE
Disable DAQ logging when compiling outside of local domains

### PR DESCRIPTION
**Pull request by jml985**
Disable DAQ logging when compiling outside of local domains

2 defines are added which should be left ignored for most offline compiles:

RTS_ENABLE_LOG
RTS_LOG_DEFAULT_NET

The first will enable logging, and it will go to stderr
The second enables logging to the main daq server, and can not be successful outside the local network.

### CODE REVIEW

**Comment by plexoos** [comment]
@jml985, could you please confirm that all the submitted changes are intended? You can do this by checking the "Files changed" tab at https://github.com/star-bnl/star-sw/pull/643/files. I am asking because there appear to be modifications beyond what the title and descriptions indicate. Are these changes minor enough to be disregarded?

**Review by genevb — APPROVED** [review]
I am not an expert on the code, but approving to help it move quickly.

**Comment by jml985** [comment]
@plexoos Yes, there were also some changes here for the daq readers of various detectors during the summer.   These could in principal be separated from this pull request if you would rather keep them independent.

**Comment by plexoos** [comment]
> These could in principal be separated from this pull request if you would rather keep them independent.

Fine by me

**Review by plexoos — APPROVED** [review]

**Comment by genevb** [comment]
> @plexoos Yes, there were also some changes here for the daq readers of various detectors during the summer. These could in principal be separated from this pull request if you would rather keep them independent.

A potential reason to separate things is that, as I understand it, we're going to want to back-propagate the DAQ-logging portion of this PR into older software libraries. The FCS, iTPC, TPC23, STGC codes did not exist in old libraries, so this PR as it stands can't simply be used as is for updating old libraries.

**Comment by plexoos** [comment]
Yes, it's a very good point Gene. Jeff, can you prepare a patch which can be applied to older libraries?

**Comment by jml985** [comment]
What is the best way to remove files from the pull request, do we drop the request and make a new one?

**Comment by plexoos** [comment]
Yes, considering there aren't many changes, it might be easier to create a new branch from the head of main, reintroduce only the relevant modifications, and then create a pull request using that new branch. Alternatively, you can use `git revert` followed by `git add -e` or `git add -p` to selectively include the relevant changes and skip the unwanted ones.

**Comment by jml985** [comment]
Ok, I'll do this after my current meeting...

-Jeff
________________________________

**Pull request closed without merging**
