### PR TITLE
[JevpProduction] Update fstBuilder for beam

### PR DESCRIPTION
**Pull request by sunxuhit**
Switch the signal cuts back to default for the beam.

### CODE REVIEW

**Comment by starsdong** [comment]
Any concern from the reviewers on this request? The requested changes seem to straightforward.
We do also have one issue with the CI Build/ROOT5 failing, any comment?

**Comment by veprbl** [comment]
The failure on the "JevpProduction" branch is a known issue and needs to be addressed separately from this PR.

**Comment by jml985** [comment]
@starsdong The issue we are having is that changes to the offline (I guess) have stopped the StRoot/RTS directory from compiling because of data type support being removed.   There was a pull request from Dmitry that fixes this for offline, but would break the experiments DAQ if back ported our code.        I'm on vacation (and still supporting the run, but not this nonsense) till january so there will be nothing done on my end till then.       On the plus side, it isn't crucial whether or not the Jevp pull requests are accepted as they are not used in the offline code anywhere.   As far as the running QA at the experiment, the PRs are incorporated and tested in the online as soon as they are submitted whether or not they pass the CI tests.   This is ugly, but even if the CI tests were working properly the review process is not quick enough for the QA updates during the run.

**Comment by starsdong** [comment]
Closing this PR. Jevp is update-to-date with the recent PR by Jeff.
https://github.com/star-bnl/star-sw/pull/292

**Pull request closed without merging**
