### PR TITLE
Update run-by-run QA to version 3

### PR DESCRIPTION
**Pull request by ssedd1123**
The v2 run-by-run is replaced by a python only v3 program for ease of maintenance and future development.

### CODE REVIEW

**Comment by plexoos** [comment]
This PR adds the following binary files:

```
StRoot/PWGTools/BadRunQA/ttf/Helvetica-Bold.ttf
StRoot/PWGTools/BadRunQA/ttf/Helvetica-BoldOblique.ttf
StRoot/PWGTools/BadRunQA/ttf/Helvetica-Oblique.ttf
StRoot/PWGTools/BadRunQA/ttf/Helvetica.ttf
StRoot/PWGTools/BadRunQA/ttf/helvetica-compressed-5871d14b6903a.otf
StRoot/PWGTools/BadRunQA/ttf/helvetica-light-587ebe5a59211.ttf
StRoot/PWGTools/BadRunQA/ttf/helvetica-rounded-bold-5871d05ead8de.otf
```

Are they really necessary and used in the "run-by-run QA"?

**Comment by ssedd1123** [comment]
These are font files for the plotting routine. They are needed to draw text with the font 'Helvetica'. It's not strictly needed as I can modify my code easily to work without them, but I will be forced to use the default font from matplotlib which is "DejaVu Sans" and my superior disliked that font. I can only guess that 'Helvetica', being the default font for Gnuplot and looks sort-of similar to ROOT's default font, is more conventional for his liking. 

If you really cannot allow those binaries to be uploaded, I will ask the QA group to settle with DejaVu Sans and re-upload my repo without ttf.

**Comment by veprbl** [comment]
@ssedd1123 What is the license for these font files? Do you have a permission to redistribute them?

**Comment by ssedd1123** [comment]
That is a good question. I did not realize I need a permission for a font, but no I don't have the permission. I will close the fork, remove the font and fork again. Sorry for my mistakes.

**Pull request closed without merging**
