### PR TITLE
Move back to MagFactor instead of starMagOnl for pre 2012 data (issue #185)

### LINKED ISSUE #185: Assert in Y2000 real data nightly tests
As reported in the status of DEV nightly test jobs...
https://www.star.bnl.gov/devcgi/weekDEVjobStatus.pl
...Three Y2000 real data tests have been crashing with asserts since 2021-10-29:

...
StiMaker:INFO  - StiMasterHitLoader::loadEvent() - TpcHitLoader loaded 99638 hits
StiDetectorContainer::begin() -I- size:540
root4star: .sl73_gcc485/obj/StRoot/Sti/StiKalmanTrackFinder.cxx:463: void StiKalmanTrackFinder::find(StiKalmanTrack*, int, StiKalmanTrackNode*, StiKalmanTrackFinder::QAFind&): Assertion `mEventPerm>=0 && "FATAL::TOO MANY permutations"' failed.

To reproduce:
root4star -b -q -l 'bfc.C(100,"p2000,VFMinuit,logger,CMuDst,NosvtIT,NossdIT","st_physics_1229021_raw_0003.daq")'

DAQ file is here:
/star/rcf/test/daq/2000/08/st_physics_1229021_raw_0003.daq

-Gene

### PR DESCRIPTION
**Pull request by fisyak**
Fix #185 
Move back to use  MagFactor instead starMagOnl for data obtained before 2012 (before starMagAvg), 
due to missing run numbers used for search in RunLog/onl DB. 
Use fixed scale to 4500 kA for starMagOnl.

### CODE REVIEW

**Comment by genevb** [comment]
@dmarkh indicated in the conversation of #185 that he modified starMagOnl to resolve this issue. Should I interpret this code change proposal as an indication that Dmitry's modification did not resolve all issues?

**Comment by dmarkh** [comment]
Yes, unfortunately, RunLog/onl/starMagOnl table is hardcoded to require
runNumber - it is one of those rare exceptions of our "beginTime only"
rules. It is nearly impossible to guarantee that all run numbers are
properly enabled, therefore roll-back to ScaleFactor (does not use
runNumber) is a better option.

-Dmitry

**Review by plexoos — APPROVED** [review]

**Review by dmarkh — APPROVED** [review]
LGTM

**Comment by genevb** [comment]
@plexoos , we'll need an SL21d_1 tag to include this patch if and when this PR is ready for merging. Thanks in advance.

**Pull request merged**
