### PR TITLE
StMuDSTMaker: fixes for TChain::kBigNumber from ROOT6

### PR DESCRIPTION
**Pull request by veprbl**

### CODE REVIEW

**Comment by plexoos** [comment]
Precompiled headers probably conceal this kind of issue.

**Comment by veprbl** [comment]
~~This PR comes without much of an obvious test, as the bfc macro is not ROOT6-ready yet.~~ edit: bfc works with root6 now

**Comment by starsdong** [comment]
Daniel, Grigory? Could you please take a review at this PR? Thanks

**Comment by starsdong** [comment]
Looks good to me. What do other reviewers think?

**Review by plexoos — APPROVED** [review]

**Comment by plexoos** [comment]
This has been pending long enough for anyone interested to comment or express concerns. The current tests do not indicate any issues so, merging.

**Pull request merged**
