### PR TITLE
Enable default STAR Spack environment

### PR DESCRIPTION
**Pull request by plexoos**

### CODE REVIEW

**Comment by genevb** [comment]
I tried this out and realized that what is needed is either that `default.config` is a copy of, or soft (symbolic) link to `config/v0.2.3-rhel7-root5.34.38-32b.config`. I understand that github can handle soft links as long as they are relative, so I expect a soft link will work fine. I tried a soft link locally and I was able to compile StRoot/StFwdTrackMaker in DEV as a test.

To be clear, what `starver` does is _source_ the `default.config` file itself, not source a file listed inside `default.config`. Here was what Jerome wrote when he established this:

"2- starver SL22a
  would ALSO source a file named $STAR/mgr/default.config
  This is to address the discussion that for a given library, there
  may actually not be multiple config."

**Comment by plexoos** [comment]
Hi Gene,
Yes, it is implemented as a soft link: `mgr/default.config -> config/v0.2.3-rhel7-root5.34.38-32b.config`

**Review by genevb — APPROVED** [review]
This works as far as I can tell.

**Comment by plexoos** [comment]
Jason @klendathu2k, Frank @fgeurts Do you approve?

**Review by fgeurts — APPROVED** [review]

**Review by klendathu2k — APPROVED** [review]
LGTM

**Pull request merged**
