### PR TITLE
Tuned T0offsets and iTPC cluster sizes for Run19 Au+Au 19.6 GeV embeding

### PR DESCRIPTION
**Pull request by zhux97**
These tunes are temporary solutions for QM22.
The details can be found in slide #5 of
https://drupal.star.bnl.gov/STAR/system/files/embedding_status_20220127.pdf
and slide #4-6 of
https://drupal.star.bnl.gov/STAR/system/files/embedding_status_20220113.pdf

### CODE REVIEW

**Comment by starsdong** [comment]
Irakli/Yuri, if you can quickly review/approve this. Let us try to merge this in soon.
Xianglei, do you need another PR to backport to SL21c?

**Comment by zhux97** [comment]
> Irakli/Yuri, if you can quickly review/approve this. Let us try to merge this in soon. Xianglei, do you need another PR to backport to SL21c?

If it is merged to 'main', maybe we don't need another PR.

**Comment by iraklic** [comment]
I can certainly approve it. Looks like quite an improvement.

**Review by iraklic — APPROVED** [review]

**Review by plexoos — APPROVED** [review]
The improvement is pretty evident from the posted plots. Thanks for the study and documentation, Xianglei

**Pull request merged**
