### PR TITLE
Fxt offset vtx

### PR DESCRIPTION
**Pull request by genevb**
This PR adjusts the selection of candidate tracks for use in Minuit vertex-finding to be offset by -2 cm from the z-axis when processing with the `FXT` chain option. The z-axis is otherwise the default for the Minuit vertex-finding `RImpact` cut.

### CODE REVIEW

**Review by iraklic — APPROVED** [review]

**Comment by fisyak** [comment]
Thie proposed  modification does not account a shift in Z position o fintecept with beam line.
I proposed  for FXT doL
+      static Double_t xBeam = 0;
+      static Double_t yBeam = -2.
+      THelixTrack thelix = gDCA->thelix();
+      Double_t step = thelix.Path(xBeam, yBeam);
+      Double_t xyz[3];
+      thelix.Eval(step, xyz);
+      Double_t dcaXY = TMath::Sqrt((xyz[0] - xBeam)*(xyz[0] - xBeam) + (xyz[1] - yBeam)*(xyz[1] - yBeam));
+      if (dcaXY  >  mRImpactMax) continue;
+      Double_t z_lin = xyz[2];

**Review by plexoos — APPROVED** [review]
Looks good!

Not sure whether the generated files should be included in the diff, though.

**Comment by genevb** [comment]
> Not sure whether the generated files should be included in the diff, though.

Can you please remind me how to remove them, @plexoos ?

And I think @fisyak is correct that the z_lin variable needs modified. I'll update that before merging.

**Comment by genevb** [comment]
@plexoos , nevermind on the file exclusion...I found instructions via internet search.

The commit I just made is mathematically identical to the proposal from @fisyak, and is also mathematically identical to the prior version for the calculation of the `RImpact` variable (I ran multiple tests with and without the -2 cm bias to confirm this).

Thanks, @fisyak and @plexoos. I'll wait for some CI checks, and then I will squash and merge.

**Pull request merged**
