### PR TITLE
Averaged magnet current to set magnetic field strength

### PR DESCRIPTION
**Pull request by fisyak**
This is the fix for problem described in 
https://drupal.star.bnl.gov/STAR/blog/fisyak/correlation-between-star-main-magnet-current-and-ks0-mass-2021-7p7-gev-and-17p3-gev-data

### CODE REVIEW

**Comment by starsdong** [comment]
Dmitry and other colleagues,

Could you please take a review at this PR and comment/approve it? This PR is planned to be included in the upcoming lib release (SL21d) that is needed for upcoming FXT production? Thanks

**Review by dmarkh — APPROVED** [review]
This PR contains TPC-specific code and an IDL file (no corresponding db table requested). IDL file correctness was verified by CI, and I'm no expert in TPC codes. But, since I was specifically asked to do a review - here we go:
I formally approve this PR (given the notes above).

**Comment by starsdong** [comment]
Thank you, Dmitry.

Irakli, among the reviewers, you are likely the most knowledgeable person for the TPC. Could you please help take a review and comment/approve this PR?

Thanks

**Review by iraklic — APPROVED** [review]

**Comment by iraklic** [comment]
> Thank you, Dmitry.
> 
> Irakli, among the reviewers, you are likely the most knowledgeable person for the TPC. Could you please help take a review and comment/approve this PR?
> 
> Thanks

Hi @starsdong , I remember looking over Yuri's blog about corrections and I thought I already took action on this. I guess it slipped me. I just approved it.


Irakli

**Comment by starsdong** [comment]
Shall we merge this in or it will be done automatically?

**Comment by plexoos** [comment]
It's never been done automatically.

**Pull request merged**
