### PR TITLE
Sync with RTS code

### PR DESCRIPTION
**Pull request by jml985**
Please do not yet review or accept this.  I will be adding files one by one to see what (if anything) breaks the CI tests

### CODE REVIEW

**Comment by plexoos** [comment]
@akioogawa @kehw Any last comments before we merge this?
As a followup, Do you think we should update the CODEOWNERS to include specific subdirs/files and accounts who actively develop/monitor the changes?

https://github.com/star-bnl/star-sw/blob/7794c768e9bbf95e2e24687738df2f1fbf2b9887/.github/CODEOWNERS#L5

**Comment by jml985** [comment]
@plexoos - The codeowners are correct.  (Me, Tonko, Akio, Hongwei).  Tonko and I are responsible for the majority of the code there, but both hongwei and akio have parts of it.

**Comment by akioogawa** [comment]
Are you done adding, @jml985?

**Review by akioogawa — APPROVED** [review]

**Comment by jml985** [comment]
@kehw Yes,   I'll be opening another for the specific Jevp code updates.   You can go ahead and accept these.

**Review by plexoos — APPROVED** [review]

**Pull request merged**
