### PR TITLE
Updated timebin handling by StFstRawHitMaker

### PR DESCRIPTION
**Pull request by jdbrice**
This is an important update that effects the ongoing Fast offline production of Run24 data.
This fixes the raw hit maker producing incorrect hits when the default number of time bins  is not correct.

### CODE REVIEW

**Comment by genevb** [comment]
The code change appears to be straightforward. The `Calibrations_fst / fstControl` database currently has only 3 entries, so is the plan to populate this database table more fully to cover 2022-2025 datasets?

    select entryTime,beginTime,kFstCurrentTimeBinNum from fstControl order by beginTime asc;
    2022-02-03 18:35:37	2021-10-25 00:00:00	9
    2022-02-04 00:59:49	2021-10-26 00:00:00	9
    2022-02-04 01:06:18	2021-12-21 17:51:51	3

Thanks,
-Gene

p.s. Not a big deal and not worth worrying about now, but this table would've been a good fit under `Conditions_fts` instead of `Calibrations_fts`.

**Review by plexoos — APPROVED** [review]

**Comment by jdbrice** [comment]
@genevb If you have no concerns could you approve this so we can merge?

**Comment by genevb** [comment]
> @genevb If you have no concerns could you approve this so we can merge?

Me: "is the plan to populate this database table more fully to cover 2022-2025 datasets?"

**Comment by jdbrice** [comment]
@genevb @akioogawa @sunxuhit 
Can we approve this and merge? Until this goes in the FastOffline has zero usable FST data

**Review by akioogawa — APPROVED** [review]

**Pull request merged**
