### PR TITLE
Testing Scheme for RTS git

### PR DESCRIPTION
**Pull request by jml985**

### CODE REVIEW

**Comment by akioogawa** [comment]
Testing testing....

**Comment by akioogawa** [comment]
I guess I have no idea how to approve

**Review by akioogawa — APPROVED** [review]

**Comment by plexoos** [comment]
I think it works but I hope all of these test commits will not end up on our main branch :)
If you really really want these on the main branch we should enable "squash merging" in order not to pollute it too much

**Review by akioogawa — APPROVED** [review]

**Comment by akioogawa** [comment]
I have no idea what I'm doing. No review button on this page. If I click one of the file, there is one and approved there. Now I approved all the files? Sorry but totally confused :P

**Comment by plexoos** [comment]
@akioogawa You can click on the "Files changed" tab on this PR page and then click on the green "Review changes" button. From the list of available options it should be straight forward what to do next

**Review by akioogawa — DISMISSED** [review]

**Review by kehw — DISMISSED** [review]
testing review PR

**Comment by plexoos** [comment]
As Jeff suggested, a more practical PR can be created proposing new code owners for StRoot/RTS and StRoot/OnlTools directories. It's better to close this one without merging

**Pull request closed without merging**
