### PR TITLE
[SL21c] Backport TPC RS changes

### PR DESCRIPTION
**Pull request by plexoos**
- Change TPX gain loading interface from fTpx->put(... to fTpx->gain_al… (#417)
- change for yuri (#429)
- update TpcRS parameters for Run19 AuAu19.6 GeV embedding (#463)
- Cherry pick RTS/src/DAQ_TPX/tpxGain.h from 6dd0b8e4

### CODE REVIEW

**Comment by starsdong** [comment]
Hi Dmitri, could you help take a look the CI build? They seem not successful and likely will need your expert knowledge to investigate. Thanks

**Comment by plexoos** [comment]
Yes, I wanted to ask you about the PRs you approved and merged.

In particular #417, I don't quite understand the purpose of this file [StRoot/StTpcHitMaker/StTpcHitMaker.flow](https://github.com/star-bnl/star-sw/pull/466/files#diff-59f6f53cd739082020149362d51c9fa31e2bf8a91fedd691a508adfe9652d79e)? I'd appreciate if you can clarify this for us.

Another ambiguity (at least for me) is in #429 merged with message "change for yuri". Can you confirm that the run compatibility with run 22 (see the patch) is appropriate for SL21c and does not affect reprocessing of real data should we need to do one in the future?

```diff

		}

-		if(do_cuts==1) {	// ADDED in FY22, pp500
+		if(do_cuts==1 && run_compatibility >= 22) {	// ADDED in FY22, pp500
			// kill ONEDPAD unless they fall before the trigger
			if((cl->t_max > 20) && (fla & FCF_ONEPAD)) return ;
		}
```

Thank you

**Comment by starsdong** [comment]
Hi Dmitri,

1) I asked Yuri about the StTpcHitMaker.flow file, and he commented this is for a documentation that he needs this.

2) I added Jeff in. My understanding is that the change only has an impact for real data in FY22+. But I should let Jeff (re-)confirm this for SL21c library (Jeff is added in the review list).

Thanks

**Comment by starsdong** [comment]
Xianglei, thanks to Dmitri for creating this PR to update the SL21c library for embedding. Since you did all the tests before, could you verify all these changes in this PR are consistent with what you tested before? Currently the CI build fails, since you did the test before, so presumably the codes should compile and run on RCF, correct? Thanks

**Comment by zhux97** [comment]
Xin, OK, I will try to test it today or tomorrow. As Dmitri wrote in the S&C management list (thanks!), the test I have done before is not exactly the test for these PR's. I will try to test the code in PR's ASAP.

**Comment by starsdong** [comment]
Thank you, Xianglei. That will be great. Cheers

**Comment by zhux97** [comment]
Thanks to Dmitri for assembling the PR#466 code, I have produced a proton test sample for Run19 AuAu19.6 GeV with SL21c + PR #466 (compiled the update RTS and StTpcHitMaker with cons). The QA plots can be found here
https://www.star.bnl.gov/protected/embedding/AutoIndex.php?dir=pr466datamc/
The previous samples, which were produced with SL21c + the whole RTS/StTpcHitMaker from .DEV2, the QA plots are
https://www.star.bnl.gov/protected/embedding/AutoIndex.php?dir=pr463datamc/
I think everything looks consistent between these two datasets.

Yuri and Tommy have confirmed that the TPC clusters from online and offline (with PR #466 code) cluster finders (SL21c) are consistent within 0.5%, see more comparison plots between online/offline cluster finders in this link:
https://www.star.bnl.gov/~ctsang/TbyT_12222022/

With this tests, I think the code in this PR are ready for merging into the SL21c branch.

**Pull request merged**
