### PR TITLE
Backport the latest TpcRS code and Run19 parameters to SL21c

### PR DESCRIPTION
**Pull request by zhux97**
These are the last 2 pieces of code needed for BES-II embedding productions.

### CODE REVIEW

**Comment by plexoos** [comment]
Is this difference intended?

```diff
$ git diff main zhux97/SL21c -- StRoot/StMcEventMaker
diff --git a/StRoot/StMcEventMaker/StMcEventMaker.cxx b/StRoot/StMcEventMaker/StMcEventMaker.cxx
index 347d842c7e..940060692b 100644
--- a/StRoot/StMcEventMaker/StMcEventMaker.cxx
+++ b/StRoot/StMcEventMaker/StMcEventMaker.cxx
@@ -1069,7 +1069,7 @@ Int_t StMcEventMaker::Make()
                long nPseudoPadrow = 0;
                long ihit;
                for(ihit=0; ihit<NHits; ihit++) {
-#if 0 /* keep all tpc hits => Inner TPC sector upgrade */
+#if 1 /* keep all tpc hits => Inner TPC sector upgrade */
                    if (tpcHitTable[ihit].volume_id < 101 || tpcHitTable[ihit].volume_id > 2472) {
                        if (tpcHitTable[ihit].volume_id <= 202472 &&
                            tpcHitTable[ihit].volume_id > 2472) nPseudoPadrow++;
```

**Comment by genevb** [comment]
> Is this difference intended?
...

@zhux97 , I think Dmitri's pointing out that no changes to StMcEventMaker are (yet) included in this PR.

Thanks,
-Gene

**Comment by plexoos** [comment]
Let me elaborate a bit more.
The SL21c branch already contains some changes to StMcEventMaker introduced in #289. It is probably not the intention of *this* PR to make additional changes in StMcEventMaker and I should have better commented in #289 about this... But, since this PR appears to be the final one before we tag SL21c, I compared it with the main branch and noticed the one line difference shown above. So, I am not sure if this was done intentionally or not.

**Comment by zhux97** [comment]
Hi Dmitri,

Thanks for pointing this out.
This modification is an intended one. The reason is explained in page # 3 of
https://drupal.star.bnl.gov/STAR/system/files/embedding_20220119.pdf


> Let me elaborate a bit more. The SL21c branch already contains some changes to StMcEventMaker introduced in #289. It is probably not the intention of _this_ PR to make additional changes in StMcEventMaker and I should have better commented in #289 about this... But, since this PR appears to be the final one before we tag SL21c, I compared it with the main branch and noticed the one line difference shown above. So, I am not sure if this was done intentionally or not.

**Pull request merged**
