### PR TITLE
StGenericVertex: Clean up #include statements

### PR DESCRIPTION
**Pull request by plexoos**
Basically, include what you use

### CODE REVIEW

**Comment by starsdong** [comment]
Jason, Akio and Victor, do you have any comments/suggestions to this request? The CI tests look good to me. Assuming they are more or less complete, it seems to be safe to make these cleanups. Thanks

**Review by klendathu2k — APPROVED** [review]
Looks reasonable.

**Comment by starsdong** [comment]
Dmitri, I think this PR is ready to be merged. Could you please update with the latest change from main and then merge this PR? Thanks

**Comment by plexoos** [comment]
> Could you please update with the latest change from main

It is not really necessary since there are no conflicts or dependency issues.

@akioogawa Are you ok with the changes?

**Pull request merged**
