### PR TITLE
Code update for Run18 embedding

### PR DESCRIPTION
**Pull request by zhux97**
Patches needed for Run18 embedding are assembled in this PR. These patches are:
* RDO map is updated and iTPC RDO is added for sector 20 in Run18.
* TpcRS parameters for the second half of Run18 27 GeV dataset is added.
* Offline cluster finder (RTS and StTpcRTSHitMaker) is updated with the correct gain interface.
* A newer StTpcRSMaker is included to correct the 1st pad row.

### CODE REVIEW

**Comment by zhux97** [comment]
Embedding test have been performed for Run18 AuAu27 GeV, the QA plots can be found in
https://www.star.bnl.gov/protected/embedding/AutoIndex.php?dir=pr481test/

**Comment by starsdong** [comment]
Xianglei, thank you very much for pushing forward. Will it be possible that you can give a (short) update on this tomorrow at the S&C meeting?

**Comment by zhux97** [comment]
Xin, I will be on travel today, probably not be able to attend the meeting. I will prepare some slides and send to the S&C list this week.

**Comment by starsdong** [comment]
Thank you, Xianglei. That would be very helpful.

**Comment by zhux97** [comment]
Hi All, I have prepared some slides to describe the updates in this PR,
https://drupal.star.bnl.gov/STAR/system/files/embedding_status_20230130_PR481_0.pdf

**Pull request merged**
