### PR TITLE
StNbdFitMaker.cxx: update centrality calculation

### PR DESCRIPTION
**Pull request by zsweger**
Updated centrality calculation to integrate the data from 0-20% and the the glauber for >20%

### CODE REVIEW

**Review by plexoos — APPROVED** [review]

**Review by plexoos — APPROVED** [review]

**Comment by zsweger** [comment]
Hi Grigory (@nigmatkulov) can you review this?

**Comment by plexoos** [comment]
If no further comments we can merge

**Comment by nigmatkulov** [comment]
Looks good!

**Review by nigmatkulov — APPROVED** [review]
Looks good

**Pull request merged**
