### PR TITLE
Backport patches for embedding (SL20c)

### PR DESCRIPTION
**Pull request by zhux97**
Patches needed for Run18 Isobar (st_physics) embedding are assembled. The patched codes are extracted from PR #466, PR #481.

### CODE REVIEW

**Comment by zhux97** [comment]
Please find some detail about this PR in the following slides
https://drupal.star.bnl.gov/STAR/system/files/embedding_status_20230226_PR498_0.pdf

**Review by genevb — COMMENTED** [review]
I've been asked by @starsdong to review this, but I've avoided commenting on other such PRs for reasons that are not best discussed here.

The changes to StTpcRTSHitMaker codes in this commit do two things of note to me:
1) The modifications made in February 2020 to address Coverity and compiler issues have been removed as if they were to be ignored.
2) The entire maxHitsPerSector and maxBinZeroHits portions of code introduced long ago have been removed, which can potentially lead to different physics results as these were designed to exclude problematic events from reconstruction.  This is essentially a modification of the reconstruction code from the version used in official productions.

**Comment by zhux97** [comment]
Hi Gene, thanks for bringing up these issues. For my educations, are these issues affecting the official real data productions? or only embedding productions?

**Comment by genevb** [comment]
> Hi Gene, thanks for bringing up these issues. For my educations, are these issues affecting the official real data productions? or only embedding productions?
> […](#)

As a generalization, the maxHitsPerSector and maxBinZeroHits cuts are in use in official productions. Specific to SL20c, which was used for official BFC productions of datasets only in Runs 17 and 18, the default cut values are in place and no study was performed to see if there were problematic events that the cuts helped us handle. That does not imply that there were no such problematic events, as the cuts would have done their job without much fanfare (only a minor notice in the production log files), and the potential is there for jobs to get hung on tracking for those events. There is also the possibility that not a single event was affected by the cuts for Runs 17 and 18 as the problematic events were more prominent in low energy collisions.

I don't understand why we would make an effort to specifically modify the code to remove these cuts.

-Gene

**Comment by zhux97** [comment]
Hi Gene, thanks for the detailed information. This portion of code indeed were removed in the latest version of StTpcRTSHitMaker. But it is still in the StTpcHitMaker. I checked one of the log file from the real data bfc production chain (which reads the online hits), but did not find the StTpcRTSHitMaker in the maker list. So I guess it is safe for real data production, isn't it? For embedding production, this piece of code will reject some high occupancy events for processing, otherwise the embedding chain will crash, right? We indeed find some small fraction of embedding jobs (on some certain daq files, less than 10 out of 1000 files) have higher probability to fail during tracking, which might be related to the missing protection in this StTpcRTSHitMaker code. Thanks!

**Comment by genevb** [comment]
Hi, Xianglei.

Yes, I think you understand correctly. StTpcHitMaker is generally used in the real data production, and StTpcRTSHitMaker is used in the embedding reconstruction. The two _should_ be configured to skip the same data. And, yes, I agree that you may be seeing symptoms in SL21d where this code was similarly modified in PR #493 , and in SL19b modified by PR #481 .

And, yes, PR #417 from a few months ago did erase the code from the current version of StTpcRTSHitMaker for new libraries (currently only SL23a and DEV, but we're about to freeze SL23b with this mess as well).

-Gene

**Comment by klendathu2k** [comment]
Just a random thought / question here.  (Or more).

Do we know what the source of the high hit multiplicity is in the 
problematic
events which these cuts are meant to address?  In other words, are they 
from the
primary collision or from pileup?  I would presume the latter.   But if 
it
really is the former, there is a bias introduced in high multiplicity 
events.

When I see the statement "different reconstruction code for real data 
and
embedding" I get nervous.  Is my understanding correct that the 
StTpcHitMaker
creates hits from clusters found online, while the StTpcRTSHitMaker must
also run the clustering code on the raw TPC data (plus any simulation 
"hits")?

If so...

Wouldn't it be better if cluster finding were split into a separate 
cluster maker,
and then we only have one maker to create TPC hits?   (Recognizing we 
may be
past the point where the effort is worth it).

Jason

**Comment by genevb** [comment]
My last post, responding to @klendathu2k .... this may not be a complete list.

https://drupal.star.bnl.gov/STAR/blog/genevb/2010/aug/26/limiting-production-events-with-large-event-counts)
https://drupal.star.bnl.gov/STAR/blog/genevb/2010/aug/31/sequential-excessively-large-tpc-events
https://drupal.star.bnl.gov/STAR/blog/genevb/2011/mar/02/rt-ticket-2099
https://drupal.star.bnl.gov/STAR/blog/genevb/2011/jun/08/issue-2131-another-big-event-class
https://drupal.star.bnl.gov/STAR/blog/genevb/bes-ii-events-large-hit-counts

-Gene

**Comment by zhux97** [comment]
Hi Gene, Jason, Dmitri, the StTpcRTSHitMaker.cxx has been updated with Xin's PR #510. Now the high occupancy protection code is restored.

**Comment by starsdong** [comment]
Dmitri, could you please take a look at the CI build? It seems to be related to the environment setup? Thanks

**Comment by plexoos** [comment]
Yes, will do

**Comment by starsdong** [comment]
Hi Dmitri, I wonder whether you have any findings from the CI build why it failed. Would be great this can be solved asap and we can proceed with the embedding production. Thanks

**Comment by starsdong** [comment]
Hi Dmitri, I am curious whether you have any findings on the failure of the CI build in this PR. The embedding team is eagerly waiting for this to be merged. Thanks

**Comment by plexoos** [comment]
The changes in this PR submitted by Xianglei pass the tests (as expected). It is somewhat unexpected and worth noting here that the SL20c branch also had to be patched to include the PicoVtxFXT option introduced after SL20c in order for the tests to work on Run 20 data samples.

**Comment by zhux97** [comment]
Dmitri, thanks a lot for more patches and merging this PR. 

Gene, could you help to deploy the latest SL20c? Both CVMFS and AFS are fine. Thanks!

**Comment by genevb** [comment]
Once Dmitri tags the library, I'll build it.

Thanks,
-Gene

**Comment by plexoos** [comment]
Hi Gene, actually I created the SL20c_3 tag yesterday, just forgot to announce.

**Comment by genevb** [comment]
Hi, Dmitri.

It looks like the star-mcgen repo wasn't given the SL20c_3 tag yet.

-Gene

**Comment by plexoos** [comment]
Right. I've tagged the latest commit on main with SL20c_3 now. I hope this is what we want.

**Comment by genevb** [comment]
> Right. I've tagged the latest commit on main with SL20c_3 now. I hope this is what we want.

@klendathu2k , @zhux97 : is the latest version of star-mcgen what we want? Or just continue with what it was before now (tagged as SL20c_2)?

**Comment by zhux97** [comment]
Gene, I have no idea about 'star-mcgen'. What codes are stored in this repo ? thanks.

**Comment by genevb** [comment]
Hi, Xianglei

Event generators like HIJING, PYTHIA, URQMD, etc.
https://github.com/star-bnl/star-mcgen/tree/main/StRoot/StarGenerator

-Gene

**Comment by zhux97** [comment]
Hi Gene,

I see. Currently, we have only single-particle embedding requests for run18 isobar and run17 pp510. So we can keep the star-mcgen as it is for now.

Thanks,
Xianglei

**Comment by klendathu2k** [comment]
Just looking at the differences between the current version of mcgen and 
SL20c_2...

https://github.com/star-bnl/star-mcgen/compare/SL20c_2...main

1) Pythia 8.3 was added / allows HI simulations using the pythia 8 
model(s)
2) Another common block was exposed in the pythia6 interface
    -- supports upsilon simulations
3) The pygive routine was exposed in pythia6
    -- this is a geant4star modification

Unless there is an open request that uses pythia6 to generate upsilons, 
then
I think we are good with SL20c_2.

Jason

**Comment by genevb** [comment]
@plexoos , the suggestion from Jason was to re-tag SL20c_2 as SL20c_3, but the SL20c_3 tag still points to a more recent version of star-mcgen. I think one of these three things needs to happen...

1) Make an argument for keeping the SL20c_3 tag at the latest version.

2) Remove the current SL20c_3 tag and re-apply it to SL20c_2.

3) Or if that is not straightforward, just create an SL20c_4 tag that is the same as SL20c_3 in star-sw and the same as SL20c_2 in star-mcgen.

Thanks,
-Gene

**Comment by plexoos** [comment]
SL20c_3 now points to the same commit as SL20c_2

**Comment by genevb** [comment]
SZL20 (SL20c_3) has been deployed on AFS. I'll start getting it built on CVMFS next.

-Gene

**Comment by zhux97** [comment]
Gene, thanks! I have submitted a test.

**Comment by zhux97** [comment]
Gene, the embedding script breaks in Sti, 

StiMaker:INFO  - TAttr::Found : usessd = 1

StiMaker:INFO  - We are StiMasterDetectorBuilder::build() and will clone the geometry if exists
StiMaker:INFO  - Timestamp check - Date/Time from chain is 20180426/83442
StiMaker:INFO  - Create a clone of VmcGeometry for reconstruction
StiMaker:ERROR - TGeoManager::CloseGeometry : you MUST call SetTopVolume() first !
StiMaker:INFO  - StiMasterDetectorBuilder::build() : Started
StiMaker:INFO  - StiMasterDetectorBuilder::build() : Calling Group Builder named: StarBuilderBuilder
StiMaker:INFO  - StiStarDetectorBuilder::useVMCGeometry : No PIPC volume

root4star: .sl73_gcc485/obj/StRoot/Sti/Star/StiStarDetectorBuilder.cxx:30: virtual void StiStarDetectorBuilder::useVMCGeometry(): Assertion `0' failed.
Abort


The full log file is /star/u/starembd/zhux/embd/P20ic/Proton_Isobar_2018.testAFS/test.log

**Comment by genevb** [comment]
Thanks for the quick test, Xianglei. Argh - the same issue each time I try to rebuild without building from scratch. That's annoying. OK....rebuilding from scratch, but probably not available until tomorrow then.

-Gene

**Comment by genevb** [comment]
Hi, Xianglei

Please give your test another try on AFS. I will rebuild from scratch on CVMFS.

Thanks,
-Gene

**Comment by zhux97** [comment]
Hi Gene,

Thanks! But now the script breaks at the beginning...

Executing bfcMixer_Tpx(10, "/gpfs01/star/embed/daq/2018/isobar/st_physics_adc_19116012_raw_3000008.daq", "/gpfs01/star/embed/tags/2018/isobar/st_physics_adc_19116012_raw_3000008.tags.root", 0, 2.5, -1.0, 1.0, -35.0, 35.0, 2.0, 14, 0.05, triggers, "P20icIsobar200", "FlatPt", 0, "st_physics_adc_19116012_raw_3000008.fzd"); ...
  *******************************************
  *                                         *
  *        W E L C O M E  to  R O O T       *
  *                                         *
  *   Version   5.34/38     12 March 2018   *
  *                                         *
  *  You are welcome to visit our Web site  *
  *          http://root.cern.ch            *
  *                                         *
  *******************************************

ROOT 5.34/38 ***@***.***, Mar 12 2018, 15:49:39 on linux)

CINT/ROOT C/C++ Interpreter version 5.18.00, July 2, 2010
Type ? for help. Commands must be C++ statements.
Enclose multiple statements between { }.
Error in <TUnixSystem::DynamicPathName>: StarRoot[.so | .dll | .dylib | .sl | .dl | .a] does not exist in .sl73_gcc485/lib:/afs/rhic.bnl.gov/star/packages/SL20c/.sl73_gcc485/lib:/afs/rhic.bnl.gov/star/ROOT/5.34.38/.sl73_gcc485/rootdeb/lib:/opt/star/sl73_gcc485/qt4/lib:/opt/star/sl73_gcc485/lib:/star/u/zhux/ucla/urqmd/lib:/afs/rhic.bnl.gov/star/ROOT/Xrootd/prod/.sl73_gcc485/lib:.:.sl73_gcc485/lib:/afs/rhic.bnl.gov/star/packages/SL20c/.sl73_gcc485/lib:/afs/rhic.bnl.gov/star/ROOT/5.34.38/.sl73_gcc485/rootdeb/lib:/opt/star/sl73_gcc485/qt4/lib:/opt/star/sl73_gcc485/lib:/star/u/zhux/ucla/urqmd/lib:/afs/rhic.bnl.gov/star/ROOT/Xrootd/prod/.sl73_gcc485/lib:/afs/rhic.bnl.gov/star/ROOT/36/5.34.38/.sl73_gcc485/rootdeb/lib:/afs/rhic.bnl.gov/star/ROOT/36/5.34.38/.sl73_gcc485/rootdeb/cint/cint/stl
...

The full log is
/star/u/starembd/zhux/embd/P20ic/Proton_Isobar_2018.testAFS/test.log2

**Comment by genevb** [comment]
Having started from scratch, I'm not sure what is going wrong there on AFS.

I also tried starting from scratch and building it on CVMFS earlier today. Maybe you can try your test there, Xianglei, and see if at least that is working?

Thanks,
-Gene

**Comment by zhux97** [comment]
Hi Gene,

The CVMFS version gives the same errors

Executing bfcMixer_Tpx(10, "/gpfs01/star/embed/daq/2018/isobar/st_physics_adc_19116012_raw_3000008.daq", "/gpfs01/star/embed/tags/2018/isobar/st_physics_adc_19116012_raw_3000008.tags.root", 0, 2.5, -1.0, 1.0, -35.0, 35.0, 2.0, 14, 0.05, triggers, "P20icIsobar200", "FlatPt", 0, "st_physics_adc_19116012_raw_3000008.fzd"); ...
  *******************************************
  *                                         *
  *        W E L C O M E  to  R O O T       *
  *                                         *
  *   Version   5.34/38     12 March 2018   *
  *                                         *
  *  You are welcome to visit our Web site  *
  *          http://root.cern.ch            *
  *                                         *
  *******************************************

ROOT 5.34/38 ***@***.***, Mar 12 2018, 15:49:39 on linux)

CINT/ROOT C/C++ Interpreter version 5.18.00, July 2, 2010
Type ? for help. Commands must be C++ statements.
Enclose multiple statements between { }.
*** Float Point Exception is OFF ***
Error in <TUnixSystem::DynamicPathName>: StarRoot[.so | .dll | .dylib | .sl | .dl | .a] does not exist in .sl73_gcc485/lib:/cvmfs/star.sdcc.bnl.gov/packages/SL20c/.sl73_gcc485/lib:/cvmfs/star.sdcc.bnl.gov/ROOT/5.34.38/.sl73_gcc485/rootdeb/lib:/cvmfs/star.sdcc.bnl.gov/x8664_sl7/opt/star/sl73_gcc485/qt4/lib:/cvmfs/star.sdcc.bnl.gov/x8664_sl7/opt/star/sl73_gcc485/lib:/star/u/zhux/ucla/urqmd/lib:.:.sl73_gcc485/lib:/cvmfs/star.sdcc.bnl.gov/packages/SL20c/.sl73_gcc485/lib:/cvmfs/star.sdcc.bnl.gov/ROOT/5.34.38/.sl73_gcc485/rootdeb/lib:/cvmfs/star.sdcc.bnl.gov/x8664_sl7/opt/star/sl73_gcc485/qt4/lib:/cvmfs/star.sdcc.bnl.gov/x8664_sl7/opt/star/sl73_gcc485/lib:/star/u/zhux/ucla/urqmd/lib:/cvmfs/star.sdcc.bnl.gov/ROOT/5.34.38/.sl73_gcc485/rootdeb/cint/cint/stl
 *** Start at Date : Thu May 18 23:17:38 2023
QAInfo:You are using STAR_LEVEL : SL20c, ROOT_LEVEL : 5.34.38 and node : rcas6001.rcf.bnl.gov

**Comment by genevb** [comment]
Thanks for the quick check.... not good. Hmmmm......
-Gene

**Pull request merged**
