### PR TITLE
Added centrality procedure instructions

### PR DESCRIPTION
**Pull request by zsweger**
Added centrality procedure instructions

### CODE REVIEW

**Comment by plexoos** [comment]
Can we avoid adding binary files in the repository?

**Comment by zsweger** [comment]
Okay we can remove those

**Comment by plexoos** [comment]
Ah... we let those root files slip in #340. Since it is still the HEAD of the main branch, I think it is ok if we force remove them.
However, my comment was about the pdf file. How do you think other users can update it when needed? Can you use the .md or .rst formats instead?

**Comment by zsweger** [comment]
Okay I've added a markdown version of the instructions and deleted the pdf!

**Review by plexoos — APPROVED** [review]

**Pull request merged**
