### PR TITLE
Remove GeoTestMaker and its dependencies

### PR DESCRIPTION
**Pull request by klendathu2k**
Removing GeoTestMaker and Stv codes from the main branch, as they no longer compile under root 6.24 and are (to my knowledge) not in use and not actively maintained.

### CODE REVIEW

**Review by genevb — APPROVED** [review]
We are not presently using Stv in any (nightly) tests, nor have we used it for any official productions. I do not think there is any fundamental issue with its removal, and it is retrievable from the code archives if there is future interest in it. So I will not oppose this removal. I don't really know anything about GeoTestMaker and I offer no comment on its removal.

**Review by plexoos — APPROVED** [review]
❤️ We should do this more often 😺

**Comment by klendathu2k** [comment]
>  I don't really know anything about GeoTestMaker and I offer no comment on its removal.

GeoTestMaker is essentially just a set of Stv utility classes.   There are no other packages in our repo that depend upon it... at least nothing showed up when (1) I grepped the codebase, and (2) I ran cons.

**Comment by genevb** [comment]
A simple search for files with "Stv" in their name reveals several other files that can probably also be removed from the library along with the Stv package, since it is unlikely that anything else uses these files.

    StDb/idl/StvHitErrs.idl
    StDb/idl/StvKonst.idl
    StDb/idl/StvTpcHitErrs.idl
    StRoot/StGenericVertexMaker/StvPPVertex
    StRoot/macros/calib/StvFitErr.C
    StRoot/macros/calib/StvFitErr.csh
    StRoot/macros/calib/runStv.C
    StarDb/Calibrations/tracker/StvIstHitErrs.C
    StarDb/Calibrations/tracker/StvKonst.C
    StarDb/Calibrations/tracker/StvPxlHitErrs.C
    StarDb/Calibrations/tracker/StvTpcInnerHitErrs.20090315.000000.C
    StarDb/Calibrations/tracker/StvTpcInnerHitErrs.20100101.000000.C
    StarDb/Calibrations/tracker/StvTpcInnerHitErrs.C
    StarDb/Calibrations/tracker/StvTpcInnerHitErrs.y2009c.C
    StarDb/Calibrations/tracker/StvTpcInnerHitErrs.y2010c.C
    StarDb/Calibrations/tracker/StvTpcInnerHitErrs.y2011c.C
    StarDb/Calibrations/tracker/StvTpcInnerPromptErrs.C
    StarDb/Calibrations/tracker/StvTpcOuterHitErrs.20090315.000000.C
    StarDb/Calibrations/tracker/StvTpcOuterHitErrs.20100101.000000.C
    StarDb/Calibrations/tracker/StvTpcOuterHitErrs.C
    StarDb/Calibrations/tracker/StvTpcOuterHitErrs.y2009c.C
    StarDb/Calibrations/tracker/StvTpcOuterHitErrs.y2010c.C
    StarDb/Calibrations/tracker/StvTpcOuterHitErrs.y2011c.C
    StarDb/Calibrations/tracker/StvTpcOuterPromptErrs.C

-Gene

**Comment by klendathu2k** [comment]
Hi Gene,

... and doing a grep for Stv reminds me that
1) There are build instructions for Stv in cons, and
2) There are chain options defined in StBFChain

... will look more closely when I have a chance.

Jason

**Comment by klendathu2k** [comment]
Drafting a new PR #607 to remove these files, and cleanup a some 
additional
Stv "dependencies"... BFC options and StXTrakMaker.  We'll see if it 
passes
the CI tests.

**Pull request merged**
