### PR TITLE
Rename files to avoid conflict on case insensitive filesystems

### PR DESCRIPTION
**Pull request by plexoos**

### CODE REVIEW

**Comment by veprbl** [comment]
@dmarkh Why?

**Comment by dmarkh** [comment]
Oops, my bad. Did not intend to close *this* request. How do I undo it?

**Comment by veprbl** [comment]
No worries, I've got you

**Comment by plexoos** [comment]
Known conflicts to resolve:

- [x]   OnlTools/OnlinePlots/icons/FileOpen.xpm
        OnlTools/OnlinePlots/icons/fileopen.xpm
- [x]   OnlTools/OnlinePlots/images/FileOpen.xpm
        OnlTools/OnlinePlots/images/fileopen.xpm
- [x]   StRoot/RTS/include/FTP/FTPC_PADKEY.h
        StRoot/RTS/include/FTP/ftpc_padkey.h
- [x]   StRoot/StMCFilter/StGENParticle.cxx
        StRoot/StMCFilter/StGenParticle.cxx
- [x]   StRoot/StMCFilter/StGENParticle.h
        StRoot/StMCFilter/StGenParticle.h
- [x]   StRoot/StarGenerator/StarLight/StarLight.h
        StRoot/StarGenerator/StarLight/starlight.h
- [x]   StRoot/macros/test/Micky.C
        StRoot/macros/test/micky.C
- [x]   StarVMC/StarBASE/macros/Differential.py
        StarVMC/StarBASE/macros/differential.py

**Comment by klendathu2k** [comment]
I assume this is conflicting w/ code in StarGenerator on case insensitive filesystems.... did not know we were supporting such.  Regardless, the change does what is advertised.  It may break some user codes, but it should be obvious for them to find the change.

**Review by klendathu2k — APPROVED** [review]
More complete review of these.  I don't see any problems with the renaming.

**Comment by plexoos** [comment]
> on case insensitive filesystems.... did not know we were supporting such

APFS (by default) is one example. Without claiming any support for MacOS, it is just nice to be able to compile the code on my laptop

**Review by veprbl — APPROVED** [review]
Tested to checkout cleanly on apfs

**Comment by plexoos** [comment]
Yes, I think it was pending long enough for all interested code owners to have a look and comment. Testing this with nightly tests is next.

**Pull request merged**
