### PR TITLE
cons: drop x86_darwin support

### PR DESCRIPTION
**Pull request by veprbl**
Following discussion in https://github.com/star-bnl/star-sw/commit/61e9d4d1df854dd67d82c583fae0dde6564abbdc#

### CODE REVIEW

**Review by genevb — COMMENTED** [review]
I know the /sw paths helped support [fink](https://www.finkproject.org) installations on Mac OS X. We never ran productions on that platform, and my understanding is that containers now provide the capability to run on that platform and others. That said, there could be users compiling for their analyses that are leveraging the /sw paths, so I would suggest widely announcing this well in advance of removal to allow for potential feedback.

**Comment by veprbl** [comment]
Right, I've added an anouncement in the changelog

**Comment by plexoos** [comment]
Are we dropping support for MacOS for good?

**Comment by yfisyak** [comment]
I am not.

 

Are we dropping support for MacOS officially?

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by plexoos** [comment]
> I am not.

I am a bit puzzled by this comment. Care to elaborate?

**Comment by starsdong** [comment]
Hi All, have we resolved the questions on this conservation? Is it still the intention now to merge this to main? Thanks

**Comment by veprbl** [comment]
I don't think we run into danger of losing some valuable work here, as we can always pick out useful bits from the git history. I'm all for darwin support, but this stuff has not been updated for a decade and it seemingly was tied to an undocumented private environment. I'd do the removal, unless @yfisyak is actually using this nowadays.

**Pull request closed without merging**
