### PR TITLE
FCS Y position change based on measurements

### PR DESCRIPTION
**Pull request by akioogawa**
FCS Y position change based on measurements
 - Geometry file changes for Y position
 - Associated StFcsDb changes for default fofsets
 - Fix StFcsDb::getHcalProjectedToEcalY()
 - Update associated Offline DB pushing macro for new detector geometry
 - Also update of Offline DB macro for fcsGain
 - A small modification on StFcsWaveformFitMaker's peak finder
 - New StSpinPool/StFcsEcalHcalMipMaker as example of finding Ecal-Hcal correlation
 - Adding tofmult and BBC/VPD/TPC vertex to StSpinPool/StFcsPi0FinderForEcal as an example

### CODE REVIEW

**Review by klendathu2k — APPROVED** [review]
Everything looks fine to me.  (I did not review SpinPool codes, as these are not to be used in production context).  

With respect to geometry.  I presume that there will be no movement of the detector between runs.  If not, we should consider setting up misalignment tables to apply run-to-run changes.

**Comment by akioogawa** [comment]
Thanks!

Yes I think StSpinPool makers will not be used in production.

After we closed Ecal & Hcal on Dec20, we have not touched detector position (we measured Y position). It is already in offline DB as fcsDetectorPosition for when we open and close. I doubt we'll ever do serious MC for open position (nor physics data taking with it). I don't think Ecal and Hcal moved run by run. So I see no need for misalignment tables for run by run.

**Comment by starsdong** [comment]
Dmitry, Daniel, Zilong, could you please take a review of the PR, comment or approve it? The changes look good to me.

**Review by zlchang — APPROVED** [review]

**Review by starsdong — APPROVED** [review]

**Comment by starsdong** [comment]
Dmitri, let us merge this in. Daniel is likely tied with preparation for the upcoming collaboration meeting.

**Pull request merged**
