### PR TITLE
Geometry y2021b

### PR DESCRIPTION
**Pull request by klendathu2k**

### CODE REVIEW

**Comment by genevb** [comment]
Also need a line in GeometryDbAliases.h, oui oui?
https://github.com/star-bnl/star-sw/blob/3271996398d2017671e5edea596f9b660fc37a1c/StRoot/StChain/GeometryDbAliases.h#L157

**Review by plexoos — APPROVED** [review]
Approved to unblock. Trusting the team’s expertise.

**Comment by klendathu2k** [comment]
Si.  Picked the wrong week to quit coffee.

> Also need a line in GeometryDbAliases.h, oui oui?
> 
> https://github.com/star-bnl/star-sw/blob/3271996398d2017671e5edea596f9b660fc37a1c/StRoot/StChain/GeometryDbAliases.h#L157

**Comment by klendathu2k** [comment]
We also need to add an entry in xgeometry.age for the simulation option.  Looking at that file, I missed adding these for the y2019 and y2020 geometries.  I add those now.


> Also need a line in GeometryDbAliases.h, oui oui?


> 
> https://github.com/star-bnl/star-sw/blob/3271996398d2017671e5edea596f9b660fc37a1c/StRoot/StChain/GeometryDbAliases.h#L157

**Review by genevb — APPROVED** [review]
That covers all I know about. I'll add BFC chain options in a separate PR.

**Review by iraklic — APPROVED** [review]

**Comment by genevb** [comment]
@klendathu2k , can we merge this?

**Pull request merged**
