### PR TITLE
Remove StRoot/StShadowMaker and "shadow" option

### PR DESCRIPTION
**Pull request by plexoos**
This code cannot be used so I propose to remove it. Alternatively, the authors could fix the implementation by providing the valid code in [StRoot/StShadowMaker](https://github.com/star-bnl/star-sw/blob/68ae73a95f62da13742401879f26f5646727954b/StRoot/StShadowMaker/StShadowMaker.cxx) but my understanding from #136 is that they are fine with just removing it.

### CODE REVIEW

**Review by genevb — COMMENTED** [review]
My understanding is that this is no longer my responsibility.

**Comment by plexoos** [comment]
As you wish. You can remove the corresponding entry from the CODEOWNERS file in order to avoid automatic notifications
https://github.com/star-bnl/star-sw/blob/68ae73a95f62da13742401879f26f5646727954b/.github/CODEOWNERS#L84

**Comment by klendathu2k** [comment]
That is not quite my reading of the discussion in #136.

StShadowMaker was used in the blinding/unblinding of data for the isobar data.  That is the reason that the implementation file is encrypted.  This code is (I believe) needed in order to be able to read / process the isobar data, and thus we need to maintain this in our library releases.  Now that the data has been unblinded, it is not clear to me that StShadowMaker should remain encrypted.  But that decision should be taken up as a topic for an S&C meeting.

**Comment by plexoos** [comment]
Just like I said:

> Alternatively, the authors could fix the implementation by providing the valid code in StRoot/StShadowMaker

Who is the author? Jerome? @jlauret

**Comment by jlauret** [comment]
This code does not need to be deployed (it is not part of the chain except the blind analysis). We can leave it encrypted and never use in a checkout. Only the header can / should be deployed.
Furthermore, I no longer have responsibility for the fate of any code in STAR remember? So, while the suggestion is already to leave it "as-is" and  not checkout upon new library release (only the header file is needed, not the code itself), @genevb  should IMO be the new owner of this piece of code.

**Comment by genevb** [comment]
A couple things that appear to need clarifying:
- StShadowMaker is not needed to read the unblinded data, which is what is now in the hands of analyzers. It is only necessary for blinding purposes.
- Jerome & I were jointly involved in preparing the StShadowMaker code and encrypting it. If there is a directive from the Collaboration (particularly the Analysis Blinding Committee) to provide it unencrypted, this is of course possible.

EDIT: I see Jerome responded at about the same time I did, so there is some overlap in what we have said.

**Comment by plexoos** [comment]
>  We can leave it encrypted and never use in a checkout.

Why? It cannot be compiled, it cannot be used.
Why do you want to complicate the life of our users by requiring a sub-standard clone procedure? I hope you do realize that the production team is not the only user who can clone and compile the entire repo?

**Comment by klendathu2k** [comment]
Alternative to removing it:  modify cons to ignore by default.

**Comment by jlauret** [comment]
> Alternative to removing it: modify cons to ignore by default.
>

Or rename .cxx.enc and move on. So many possibilities ...

**Comment by plexoos** [comment]
> modify cons to ignore by default.

Exactly my proposal #69 since July 26

**Comment by genevb** [comment]
> As you wish. You can remove the corresponding entry from the CODEOWNERS file in order to avoid automatic notifications
> 
> https://github.com/star-bnl/star-sw/blob/68ae73a95f62da13742401879f26f5646727954b/.github/CODEOWNERS#L84

My understanding != my wish
And apparently CODEOWNERS != responsibility for maintaining code (this point was made in #69 )

**Comment by plexoos** [comment]
> My understanding != my wish

It's up to you

> And apparently CODEOWNERS != responsibility for maintaining code (this point was made in #69 )

Your point != policy adopted by the collaboration. If there is a document describing the procedure of who and how can modify the code then please let us know.

**Pull request closed without merging**
