### PR TITLE
Update pams/sim/gstar/gstar_part.g

### PR DESCRIPTION
**Pull request by zhux97**
updated the K0*(892) mass and width according to the latest PDG values.

### CODE REVIEW

**Review by klendathu2k — APPROVED** [review]
Looks good.

**Comment by klendathu2k** [comment]
Need one more review from @akioogawa in order to merge...

**Review by plexoos — APPROVED** [review]

**Comment by klendathu2k** [comment]
Thanks Dmitri.  Merging now.

**Comment by plexoos** [comment]
> Need one more review from @akioogawa in order to merge...

For the merge button to turn on green: Each modified file with designated owners needs to get an approval from an owner but the requirement of two approvals can be fulfilled by anyone with a push access (not necessarily an owner). Currently, there are 24 members who can push directly to the repository https://github.com/orgs/star-bnl/teams/star-sw-codeowners/members

**Pull request merged**
