### PR TITLE
TpcRTSHitMaker update for skipping high occupancy events

### PR DESCRIPTION
**Pull request by starsdong**
Restore protection code for high occupancy events to avoid long-hung in production jobs

### CODE REVIEW

**Review by fisyak — APPROVED** [review]

**Comment by starsdong** [comment]
Added Xianglei to the reviewer list. Xianglei, I wonder whether you can give a test on the embedding job with this PR before we can merge it. Thanks

**Comment by genevb** [comment]
> Added Xianglei to the reviewer list. Xianglei, I wonder whether you can give a test on the embedding job with this PR before we can merge it. Thanks

Preferably a job that was hanging previously if there is one. I can help look for one if I'm pointed to some candidate logs to search.

**Comment by starsdong** [comment]
Xianglei, I am going to merge this one in preparation for building the SL23b library and proceed with data production. Please feel free to share your finding at this PR later. Thanks

**Comment by zhux97** [comment]
Hi all, I have made a test for this update with Run19 AuAu14.6 embedding. All jobs finished. Although a few jobs still broke in Sti due to memory issue, they eventually finished properly after the resubmissions. 
The data can be found in
/star/data105/embedding/production_14p5GeV_2019/AntiProton_400_20221603/
base QA:
https://www.star.bnl.gov/protected/embedding/SL21c_Run19_AuAu15/qa_2019_P21ic_anti_proton_fset400.pdf
log files:
/star/embed/log/AntiProton_400_20221603/log/
So everything seems to be fine. We should move forward to patch this code for other embedding libraries.

**Comment by starsdong** [comment]
Thank you, Xianglei for providing this nice check.

**Pull request merged**
