### PR TITLE
StPicoEvent: fix some potential compilation errors/warnings

### LINKED ISSUE #142: StPicoEvent doesn't compile with modern compilers
On macOS with
```
clang version 7.1.0 (tags/RELEASE_710/final)
```

I get
```c++
./StPicoHelix.h:221:11: error: no member named 'finite' in the global namespace; did you mean 'isfinite'?
  if ( !::finite(mDipAngle) ) {
        ~~^~~~~~
          isfinite
/nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/math.h:439:1: note: 'isfinite' declared here
isfinite(_A1 __lcpp_x) _NOEXCEPT
^
In file included from StPicoPhysicalHelix.cxx:9:
./StPicoHelix.h:224:11: error: no member named 'finite' in the global namespace; did you mean 'isfinite'?
  if ( !::finite(mCurvature) ) {
        ~~^~~~~~
          isfinite
/nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/math.h:439:1: note: 'isfinite' declared here
isfinite(_A1 __lcpp_x) _NOEXCEPT
^
In file included from StPicoPhysicalHelix.cxx:9:
./StPicoHelix.h:243:13: error: no member named 'finite' in the global namespace; did you mean 'isfinite'?
    if ( !::finite( tmpVal ) ) {
          ~~^~~~~~
            isfinite
/nix/store/znv06z6pld0ivwddj52rishggwc2m94c-libcxx-7.1.0-dev/include/c++/v1/math.h:439:1: note: 'isfinite' declared here
isfinite(_A1 __lcpp_x) _NOEXCEPT
^
3 errors generated.
make: *** [Makefile:23: StPicoPhysicalHelix.o] Error 1
```

On macOS with
```
gcc version 10.3.0 (GCC)
```
```c++
In file included from StPicoPhysicalHelix.cxx:9:
StPicoHelix.h: In member function ‘Int_t StPicoHelix::bad(Double_t) const’:
StPicoHelix.h:221:11: error: ‘::finite’ has not been declared; did you mean ‘fwrite’?
  221 |   if ( !::finite(mDipAngle) ) {
      |           ^~~~~~
      |           fwrite
StPicoHelix.h:224:11: error: ‘::finite’ has not been declared; did you mean ‘fwrite’?
  224 |   if ( !::finite(mCurvature) ) {
      |           ^~~~~~
      |           fwrite
StPicoHelix.h:243:13: error: ‘::finite’ has not been declared; did you mean ‘fwrite’?
  243 |     if ( !::finite( tmpVal ) ) {
      |             ^~~~~~
      |             fwrite
```

## Steps to reproduce ##
```
cd StRoot/StPicoEvent
make
```

### PR DESCRIPTION
**Pull request by veprbl**
Fixes: #142

### CODE REVIEW

**Review by plexoos — APPROVED** [review]
All of the proposed changes look reasonable to me

**Comment by plexoos** [comment]
Any objections from anyone to merging these technical fixes?

**Comment by plexoos** [comment]
> Any objections from anyone to merging these technical fixes?

Seems like no objections 🤞

**Comment by nigmatkulov** [comment]
Will this solution work with old compilers?

**Comment by plexoos** [comment]
Yes.

**Pull request merged**
