### PR TITLE
Add local DB parameters for TpcRS 26p5GeV_fixedTarget_2018

### PR DESCRIPTION
**Pull request by plexoos**
This replaces #88 due to the original PR branch removed by the submitter

Screen Shot 2021-08-19 at 11 16 58 AM

Close #88 when merged

### CODE REVIEW

**Comment by plexoos** [comment]
Already approved by @iraklic and @yfisyak

**Comment by iraklic** [comment]
@plexoos this is a little confusing. what happened here. Did you remove the comments and made a new PR?

**Comment by plexoos** [comment]
Yes

**Comment by iraklic** [comment]
got it. and looks like it does not need a new approval, right?

**Comment by plexoos** [comment]
Yes, approved in the original #88. Thank you

**Comment by genevb** [comment]
Just an FYI on this...
Because these parameters are stored as CINT files in the code library instead of in the database, any embedding/simulation libraries that need these parameters must be re-tagged when including this. At this point my understanding is that **SL19e** needs this and will need an `SL19e_2` tag. I'm looking into whether anything else needs updated in **SL19e** before we move forward with the tag.

**Pull request merged**
