### PR TITLE
build: drop warn-to-error conversion for removed packages

### PR DESCRIPTION
**Pull request by plexoos**

### CODE REVIEW

**Review by klendathu2k — APPROVED** [review]
Looks good.

**Review by genevb — COMMENTED** [review]
ok

**Review by genevb — APPROVED** [review]

**Review by genevb — COMMENTED** [review]
We also removed StRoot/StXTrakMaker, so drop that too?

**Comment by genevb** [comment]
...and StarVMC/GeoTestMaker. Did I miss any others?

**Review by iraklic — APPROVED** [review]

**Comment by plexoos** [comment]
Thank you Gene, I removed them as well

**Pull request merged**
